// Code generated by protoc-gen-grpc-gateway-cors
// source: tiller.proto
// DO NOT EDIT!

/*
Package v2 is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package v2

import "github.com/grpc-ecosystem/grpc-gateway/runtime"

// ExportReleaseServiceCorsPatterns returns an array of grpc gatway mux patterns for
// ReleaseService service to enable CORS.
func ExportReleaseServiceCorsPatterns() []runtime.Pattern {
	return []runtime.Pattern{
		pattern_ReleaseService_ListReleases_0,
		pattern_ReleaseService_SummarizeReleases_0,
		pattern_ReleaseService_GetReleaseStatus_0,
		pattern_ReleaseService_GetReleaseContent_0,
		pattern_ReleaseService_UpdateRelease_0,
		pattern_ReleaseService_InstallRelease_0,
		pattern_ReleaseService_UninstallRelease_0,
		pattern_ReleaseService_GetVersion_0,
		pattern_ReleaseService_RollbackRelease_0,
		pattern_ReleaseService_GetHistory_0,
	}
}
