// Code generated by protoc-gen-grpc-gateway-cors
// source: app.proto
// DO NOT EDIT!

/*
Package v1beta1 is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package v1beta1

import "github.com/grpc-ecosystem/grpc-gateway/runtime"

// ExportAppsCorsPatterns returns an array of grpc gatway mux patterns for
// Apps service to enable CORS.
func ExportAppsCorsPatterns() []runtime.Pattern {
	return []runtime.Pattern{
		pattern_Apps_Hello_0,
	}
}
