// Code generated by protoc-gen-go. DO NOT EDIT.
// source: app.proto

/*
Package v1beta1 is a generated protocol buffer package.

It is generated from these files:
	app.proto
	tiller.proto

It has these top-level messages:
	HelloRequest
	HelloResponse
	ListReleasesRequest
	ListSort
	ListReleasesResponse
	GetReleaseStatusRequest
	GetReleaseStatusResponse
	GetReleaseContentRequest
	GetReleaseContentResponse
	UpdateReleaseRequest
	UpdateReleaseResponse
	RollbackReleaseRequest
	RollbackReleaseResponse
	InstallReleaseRequest
	InstallReleaseResponse
	UninstallReleaseRequest
	UninstallReleaseResponse
	GetVersionRequest
	GetVersionResponse
	GetHistoryRequest
	GetHistoryResponse
	TestReleaseRequest
	TestReleaseResponse
*/
package v1beta1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import _ "github.com/grpc-ecosystem/grpc-gateway/third_party/appscodeapis/appscode/api"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HelloRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *HelloRequest) Reset()                    { *m = HelloRequest{} }
func (m *HelloRequest) String() string            { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()               {}
func (*HelloRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloResponse struct {
	Greetings string `protobuf:"bytes,1,opt,name=greetings" json:"greetings,omitempty"`
}

func (m *HelloResponse) Reset()                    { *m = HelloResponse{} }
func (m *HelloResponse) String() string            { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()               {}
func (*HelloResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HelloResponse) GetGreetings() string {
	if m != nil {
		return m.Greetings
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "appscode.seed.app.v1beta1.HelloRequest")
	proto.RegisterType((*HelloResponse)(nil), "appscode.seed.app.v1beta1.HelloResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Apps service

type AppsClient interface {
	Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
}

type appsClient struct {
	cc *grpc.ClientConn
}

func NewAppsClient(cc *grpc.ClientConn) AppsClient {
	return &appsClient{cc}
}

func (c *appsClient) Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := grpc.Invoke(ctx, "/appscode.seed.app.v1beta1.Apps/Hello", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Apps service

type AppsServer interface {
	Hello(context.Context, *HelloRequest) (*HelloResponse, error)
}

func RegisterAppsServer(s *grpc.Server, srv AppsServer) {
	s.RegisterService(&_Apps_serviceDesc, srv)
}

func _Apps_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppsServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appscode.seed.app.v1beta1.Apps/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppsServer).Hello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Apps_serviceDesc = grpc.ServiceDesc{
	ServiceName: "appscode.seed.app.v1beta1.Apps",
	HandlerType: (*AppsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _Apps_Hello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app.proto",
}

func init() { proto.RegisterFile("app.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 247 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x2c, 0x28, 0xd0,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x92, 0x4c, 0x2c, 0x28, 0x28, 0x4e, 0xce, 0x4f, 0x49, 0xd5,
	0x2b, 0x4e, 0x4d, 0x4d, 0xd1, 0x03, 0x49, 0x94, 0x19, 0x26, 0xa5, 0x96, 0x24, 0x1a, 0x4a, 0xc9,
	0xa4, 0xe7, 0xe7, 0xa7, 0xe7, 0xa4, 0xea, 0x27, 0x16, 0x64, 0xea, 0x27, 0xe6, 0xe5, 0xe5, 0x97,
	0x24, 0x96, 0x64, 0xe6, 0xe7, 0x15, 0x43, 0x34, 0x4a, 0xc9, 0xc1, 0x34, 0x62, 0x97, 0x57, 0x52,
	0xe2, 0xe2, 0xf1, 0x48, 0xcd, 0xc9, 0xc9, 0x0f, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12,
	0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x95,
	0x74, 0xb9, 0x78, 0xa1, 0x6a, 0x8a, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0x64, 0xb8, 0x38, 0xd3,
	0x8b, 0x52, 0x53, 0x4b, 0x32, 0xf3, 0xd2, 0x8b, 0xa1, 0x2a, 0x11, 0x02, 0x46, 0x33, 0x19, 0xb9,
	0x58, 0x1c, 0x0b, 0x0a, 0x8a, 0x85, 0x26, 0x30, 0x72, 0xb1, 0x82, 0x35, 0x0a, 0xa9, 0xeb, 0xe1,
	0x74, 0xbf, 0x1e, 0xb2, 0xf5, 0x52, 0x1a, 0x84, 0x15, 0x42, 0xdc, 0xa0, 0x64, 0xd2, 0xb4, 0x55,
	0x82, 0x89, 0x83, 0xb1, 0xe9, 0xf2, 0x93, 0xc9, 0x4c, 0x1a, 0x42, 0x6a, 0xfa, 0xf1, 0x28, 0x1e,
	0x05, 0x69, 0xd6, 0x87, 0x6a, 0xd4, 0x07, 0xc9, 0xe8, 0x67, 0x80, 0x74, 0x3b, 0x99, 0x70, 0xc9,
	0x26, 0xe7, 0xe7, 0xe2, 0xb6, 0xc4, 0x89, 0xc3, 0xb1, 0xa0, 0x20, 0x00, 0x14, 0x32, 0x01, 0x8c,
	0x51, 0xec, 0x50, 0xc1, 0x24, 0x36, 0x70, 0x58, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x5b,
	0x7d, 0x00, 0xb7, 0x91, 0x01, 0x00, 0x00,
}
