// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tiller.proto

package v1beta1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import hapi_chart3 "k8s.io/helm/pkg/proto/hapi/chart"
import hapi_chart "k8s.io/helm/pkg/proto/hapi/chart"
import hapi_release5 "k8s.io/helm/pkg/proto/hapi/release"
import hapi_release4 "k8s.io/helm/pkg/proto/hapi/release"
import hapi_release1 "k8s.io/helm/pkg/proto/hapi/release"
import hapi_release3 "k8s.io/helm/pkg/proto/hapi/release"
import hapi_version "k8s.io/helm/pkg/proto/hapi/version"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import _ "github.com/grpc-ecosystem/grpc-gateway/third_party/appscodeapis/appscode/api"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// SortBy defines sort operations.
type ListSort_SortBy int32

const (
	ListSort_UNKNOWN       ListSort_SortBy = 0
	ListSort_NAME          ListSort_SortBy = 1
	ListSort_LAST_RELEASED ListSort_SortBy = 2
)

var ListSort_SortBy_name = map[int32]string{
	0: "UNKNOWN",
	1: "NAME",
	2: "LAST_RELEASED",
}
var ListSort_SortBy_value = map[string]int32{
	"UNKNOWN":       0,
	"NAME":          1,
	"LAST_RELEASED": 2,
}

func (x ListSort_SortBy) String() string {
	return proto.EnumName(ListSort_SortBy_name, int32(x))
}
func (ListSort_SortBy) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{1, 0} }

// SortOrder defines sort orders to augment sorting operations.
type ListSort_SortOrder int32

const (
	ListSort_ASC  ListSort_SortOrder = 0
	ListSort_DESC ListSort_SortOrder = 1
)

var ListSort_SortOrder_name = map[int32]string{
	0: "ASC",
	1: "DESC",
}
var ListSort_SortOrder_value = map[string]int32{
	"ASC":  0,
	"DESC": 1,
}

func (x ListSort_SortOrder) String() string {
	return proto.EnumName(ListSort_SortOrder_name, int32(x))
}
func (ListSort_SortOrder) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{1, 1} }

// ListReleasesRequest requests a list of releases.
//
// Releases can be retrieved in chunks by setting limit and offset.
//
// Releases can be sorted according to a few pre-determined sort stategies.
type ListReleasesRequest struct {
	// Limit is the maximum number of releases to be returned.
	Limit int64 `protobuf:"varint,1,opt,name=limit" json:"limit,omitempty"`
	// Offset is the last release name that was seen. The next listing
	// operation will start with the name after this one.
	// Example: If list one returns albert, bernie, carl, and sets 'next: dennis'.
	// dennis is the offset. Supplying 'dennis' for the next request should
	// cause the next batch to return a set of results starting with 'dennis'.
	Offset string `protobuf:"bytes,2,opt,name=offset" json:"offset,omitempty"`
	// SortBy is the sort field that the ListReleases server should sort data before returning.
	SortBy ListSort_SortBy `protobuf:"varint,3,opt,name=sort_by,json=sortBy,enum=appscode.seed.app.v1beta1.ListSort_SortBy" json:"sort_by,omitempty"`
	// Filter is a regular expression used to filter which releases should be listed.
	//
	// Anything that matches the regexp will be included in the results.
	Filter string `protobuf:"bytes,4,opt,name=filter" json:"filter,omitempty"`
	// SortOrder is the ordering directive used for sorting.
	SortOrder   ListSort_SortOrder          `protobuf:"varint,5,opt,name=sort_order,json=sortOrder,enum=appscode.seed.app.v1beta1.ListSort_SortOrder" json:"sort_order,omitempty"`
	StatusCodes []hapi_release3.Status_Code `protobuf:"varint,6,rep,packed,name=status_codes,json=statusCodes,enum=hapi.release.Status_Code" json:"status_codes,omitempty"`
	// Namespace is the filter to select releases only from a specific namespace.
	Namespace string `protobuf:"bytes,7,opt,name=namespace" json:"namespace,omitempty"`
}

func (m *ListReleasesRequest) Reset()                    { *m = ListReleasesRequest{} }
func (m *ListReleasesRequest) String() string            { return proto.CompactTextString(m) }
func (*ListReleasesRequest) ProtoMessage()               {}
func (*ListReleasesRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *ListReleasesRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListReleasesRequest) GetOffset() string {
	if m != nil {
		return m.Offset
	}
	return ""
}

func (m *ListReleasesRequest) GetSortBy() ListSort_SortBy {
	if m != nil {
		return m.SortBy
	}
	return ListSort_UNKNOWN
}

func (m *ListReleasesRequest) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

func (m *ListReleasesRequest) GetSortOrder() ListSort_SortOrder {
	if m != nil {
		return m.SortOrder
	}
	return ListSort_ASC
}

func (m *ListReleasesRequest) GetStatusCodes() []hapi_release3.Status_Code {
	if m != nil {
		return m.StatusCodes
	}
	return nil
}

func (m *ListReleasesRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

// ListSort defines sorting fields on a release list.
type ListSort struct {
}

func (m *ListSort) Reset()                    { *m = ListSort{} }
func (m *ListSort) String() string            { return proto.CompactTextString(m) }
func (*ListSort) ProtoMessage()               {}
func (*ListSort) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

// ListReleasesResponse is a list of releases.
type ListReleasesResponse struct {
	// Count is the expected total number of releases to be returned.
	Count int64 `protobuf:"varint,1,opt,name=count" json:"count,omitempty"`
	// Next is the name of the next release. If this is other than an empty
	// string, it means there are more results.
	Next string `protobuf:"bytes,2,opt,name=next" json:"next,omitempty"`
	// Total is the total number of queryable releases.
	Total int64 `protobuf:"varint,3,opt,name=total" json:"total,omitempty"`
	// Releases is the list of found release objects.
	Releases []*hapi_release5.Release `protobuf:"bytes,4,rep,name=releases" json:"releases,omitempty"`
}

func (m *ListReleasesResponse) Reset()                    { *m = ListReleasesResponse{} }
func (m *ListReleasesResponse) String() string            { return proto.CompactTextString(m) }
func (*ListReleasesResponse) ProtoMessage()               {}
func (*ListReleasesResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *ListReleasesResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *ListReleasesResponse) GetNext() string {
	if m != nil {
		return m.Next
	}
	return ""
}

func (m *ListReleasesResponse) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ListReleasesResponse) GetReleases() []*hapi_release5.Release {
	if m != nil {
		return m.Releases
	}
	return nil
}

// GetReleaseStatusRequest is a request to get the status of a release.
type GetReleaseStatusRequest struct {
	// Name is the name of the release
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// Version is the version of the release
	Version int32 `protobuf:"varint,2,opt,name=version" json:"version,omitempty"`
}

func (m *GetReleaseStatusRequest) Reset()                    { *m = GetReleaseStatusRequest{} }
func (m *GetReleaseStatusRequest) String() string            { return proto.CompactTextString(m) }
func (*GetReleaseStatusRequest) ProtoMessage()               {}
func (*GetReleaseStatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *GetReleaseStatusRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetReleaseStatusRequest) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

// GetReleaseStatusResponse is the response indicating the status of the named release.
type GetReleaseStatusResponse struct {
	// Name is the name of the release.
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// Info contains information about the release.
	Info *hapi_release4.Info `protobuf:"bytes,2,opt,name=info" json:"info,omitempty"`
	// Namesapce the release was released into
	Namespace string `protobuf:"bytes,3,opt,name=namespace" json:"namespace,omitempty"`
}

func (m *GetReleaseStatusResponse) Reset()                    { *m = GetReleaseStatusResponse{} }
func (m *GetReleaseStatusResponse) String() string            { return proto.CompactTextString(m) }
func (*GetReleaseStatusResponse) ProtoMessage()               {}
func (*GetReleaseStatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *GetReleaseStatusResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetReleaseStatusResponse) GetInfo() *hapi_release4.Info {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *GetReleaseStatusResponse) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

// GetReleaseContentRequest is a request to get the contents of a release.
type GetReleaseContentRequest struct {
	// The name of the release
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// Version is the version of the release
	Version int32 `protobuf:"varint,2,opt,name=version" json:"version,omitempty"`
}

func (m *GetReleaseContentRequest) Reset()                    { *m = GetReleaseContentRequest{} }
func (m *GetReleaseContentRequest) String() string            { return proto.CompactTextString(m) }
func (*GetReleaseContentRequest) ProtoMessage()               {}
func (*GetReleaseContentRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *GetReleaseContentRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetReleaseContentRequest) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

// GetReleaseContentResponse is a response containing the contents of a release.
type GetReleaseContentResponse struct {
	// The release content
	Release *hapi_release5.Release `protobuf:"bytes,1,opt,name=release" json:"release,omitempty"`
}

func (m *GetReleaseContentResponse) Reset()                    { *m = GetReleaseContentResponse{} }
func (m *GetReleaseContentResponse) String() string            { return proto.CompactTextString(m) }
func (*GetReleaseContentResponse) ProtoMessage()               {}
func (*GetReleaseContentResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *GetReleaseContentResponse) GetRelease() *hapi_release5.Release {
	if m != nil {
		return m.Release
	}
	return nil
}

// UpdateReleaseRequest updates a release.
type UpdateReleaseRequest struct {
	// The name of the release
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// Chart is the protobuf representation of a chart.
	Chart *hapi_chart3.Chart `protobuf:"bytes,2,opt,name=chart" json:"chart,omitempty"`
	// Values is a string containing (unparsed) YAML values.
	Values *hapi_chart.Config `protobuf:"bytes,3,opt,name=values" json:"values,omitempty"`
	// dry_run, if true, will run through the release logic, but neither create
	DryRun bool `protobuf:"varint,4,opt,name=dry_run,json=dryRun" json:"dry_run,omitempty"`
	// DisableHooks causes the server to skip running any hooks for the upgrade.
	DisableHooks bool `protobuf:"varint,5,opt,name=disable_hooks,json=disableHooks" json:"disable_hooks,omitempty"`
	// Performs pods restart for resources if applicable
	Recreate bool `protobuf:"varint,6,opt,name=recreate" json:"recreate,omitempty"`
	// timeout specifies the max amount of time any kubernetes client command can run.
	Timeout int64 `protobuf:"varint,7,opt,name=timeout" json:"timeout,omitempty"`
	// ResetValues will cause Tiller to ignore stored values, resetting to default values.
	ResetValues bool `protobuf:"varint,8,opt,name=reset_values,json=resetValues" json:"reset_values,omitempty"`
	// wait, if true, will wait until all Pods, PVCs, and Services are in a ready state
	// before marking the release as successful. It will wait for as long as timeout
	Wait bool `protobuf:"varint,9,opt,name=wait" json:"wait,omitempty"`
	// ReuseValues will cause Tiller to reuse the values from the last release.
	// This is ignored if reset_values is set.
	ReuseValues bool `protobuf:"varint,10,opt,name=reuse_values,json=reuseValues" json:"reuse_values,omitempty"`
	// Force resource update through delete/recreate if needed.
	Force bool `protobuf:"varint,11,opt,name=force" json:"force,omitempty"`
}

func (m *UpdateReleaseRequest) Reset()                    { *m = UpdateReleaseRequest{} }
func (m *UpdateReleaseRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateReleaseRequest) ProtoMessage()               {}
func (*UpdateReleaseRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *UpdateReleaseRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateReleaseRequest) GetChart() *hapi_chart3.Chart {
	if m != nil {
		return m.Chart
	}
	return nil
}

func (m *UpdateReleaseRequest) GetValues() *hapi_chart.Config {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *UpdateReleaseRequest) GetDryRun() bool {
	if m != nil {
		return m.DryRun
	}
	return false
}

func (m *UpdateReleaseRequest) GetDisableHooks() bool {
	if m != nil {
		return m.DisableHooks
	}
	return false
}

func (m *UpdateReleaseRequest) GetRecreate() bool {
	if m != nil {
		return m.Recreate
	}
	return false
}

func (m *UpdateReleaseRequest) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *UpdateReleaseRequest) GetResetValues() bool {
	if m != nil {
		return m.ResetValues
	}
	return false
}

func (m *UpdateReleaseRequest) GetWait() bool {
	if m != nil {
		return m.Wait
	}
	return false
}

func (m *UpdateReleaseRequest) GetReuseValues() bool {
	if m != nil {
		return m.ReuseValues
	}
	return false
}

func (m *UpdateReleaseRequest) GetForce() bool {
	if m != nil {
		return m.Force
	}
	return false
}

// UpdateReleaseResponse is the response to an update request.
type UpdateReleaseResponse struct {
	Release *hapi_release5.Release `protobuf:"bytes,1,opt,name=release" json:"release,omitempty"`
}

func (m *UpdateReleaseResponse) Reset()                    { *m = UpdateReleaseResponse{} }
func (m *UpdateReleaseResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateReleaseResponse) ProtoMessage()               {}
func (*UpdateReleaseResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

func (m *UpdateReleaseResponse) GetRelease() *hapi_release5.Release {
	if m != nil {
		return m.Release
	}
	return nil
}

type RollbackReleaseRequest struct {
	// The name of the release
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// dry_run, if true, will run through the release logic but no create
	DryRun bool `protobuf:"varint,2,opt,name=dry_run,json=dryRun" json:"dry_run,omitempty"`
	// DisableHooks causes the server to skip running any hooks for the rollback
	DisableHooks bool `protobuf:"varint,3,opt,name=disable_hooks,json=disableHooks" json:"disable_hooks,omitempty"`
	// Version is the version of the release to deploy.
	Version int32 `protobuf:"varint,4,opt,name=version" json:"version,omitempty"`
	// Performs pods restart for resources if applicable
	Recreate bool `protobuf:"varint,5,opt,name=recreate" json:"recreate,omitempty"`
	// timeout specifies the max amount of time any kubernetes client command can run.
	Timeout int64 `protobuf:"varint,6,opt,name=timeout" json:"timeout,omitempty"`
	// wait, if true, will wait until all Pods, PVCs, and Services are in a ready state
	// before marking the release as successful. It will wait for as long as timeout
	Wait bool `protobuf:"varint,7,opt,name=wait" json:"wait,omitempty"`
	// Force resource update through delete/recreate if needed.
	Force bool `protobuf:"varint,8,opt,name=force" json:"force,omitempty"`
}

func (m *RollbackReleaseRequest) Reset()                    { *m = RollbackReleaseRequest{} }
func (m *RollbackReleaseRequest) String() string            { return proto.CompactTextString(m) }
func (*RollbackReleaseRequest) ProtoMessage()               {}
func (*RollbackReleaseRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

func (m *RollbackReleaseRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RollbackReleaseRequest) GetDryRun() bool {
	if m != nil {
		return m.DryRun
	}
	return false
}

func (m *RollbackReleaseRequest) GetDisableHooks() bool {
	if m != nil {
		return m.DisableHooks
	}
	return false
}

func (m *RollbackReleaseRequest) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *RollbackReleaseRequest) GetRecreate() bool {
	if m != nil {
		return m.Recreate
	}
	return false
}

func (m *RollbackReleaseRequest) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *RollbackReleaseRequest) GetWait() bool {
	if m != nil {
		return m.Wait
	}
	return false
}

func (m *RollbackReleaseRequest) GetForce() bool {
	if m != nil {
		return m.Force
	}
	return false
}

// RollbackReleaseResponse is the response to an update request.
type RollbackReleaseResponse struct {
	Release *hapi_release5.Release `protobuf:"bytes,1,opt,name=release" json:"release,omitempty"`
}

func (m *RollbackReleaseResponse) Reset()                    { *m = RollbackReleaseResponse{} }
func (m *RollbackReleaseResponse) String() string            { return proto.CompactTextString(m) }
func (*RollbackReleaseResponse) ProtoMessage()               {}
func (*RollbackReleaseResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{10} }

func (m *RollbackReleaseResponse) GetRelease() *hapi_release5.Release {
	if m != nil {
		return m.Release
	}
	return nil
}

// InstallReleaseRequest is the request for an installation of a chart.
type InstallReleaseRequest struct {
	// Chart is the protobuf representation of a chart.
	Chart *hapi_chart3.Chart `protobuf:"bytes,1,opt,name=chart" json:"chart,omitempty"`
	// Values is a string containing (unparsed) YAML values.
	Values *hapi_chart.Config `protobuf:"bytes,2,opt,name=values" json:"values,omitempty"`
	// DryRun, if true, will run through the release logic, but neither create
	// a release object nor deploy to Kubernetes. The release object returned
	// in the response will be fake.
	DryRun bool `protobuf:"varint,3,opt,name=dry_run,json=dryRun" json:"dry_run,omitempty"`
	// Name is the candidate release name. This must be unique to the
	// namespace, otherwise the server will return an error. If it is not
	// supplied, the server will autogenerate one.
	Name string `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	// DisableHooks causes the server to skip running any hooks for the install.
	DisableHooks bool `protobuf:"varint,5,opt,name=disable_hooks,json=disableHooks" json:"disable_hooks,omitempty"`
	// Namepace is the kubernetes namespace of the release.
	Namespace string `protobuf:"bytes,6,opt,name=namespace" json:"namespace,omitempty"`
	// ReuseName requests that Tiller re-uses a name, instead of erroring out.
	ReuseName bool `protobuf:"varint,7,opt,name=reuse_name,json=reuseName" json:"reuse_name,omitempty"`
	// timeout specifies the max amount of time any kubernetes client command can run.
	Timeout int64 `protobuf:"varint,8,opt,name=timeout" json:"timeout,omitempty"`
	// wait, if true, will wait until all Pods, PVCs, and Services are in a ready state
	// before marking the release as successful. It will wait for as long as timeout
	Wait bool `protobuf:"varint,9,opt,name=wait" json:"wait,omitempty"`
}

func (m *InstallReleaseRequest) Reset()                    { *m = InstallReleaseRequest{} }
func (m *InstallReleaseRequest) String() string            { return proto.CompactTextString(m) }
func (*InstallReleaseRequest) ProtoMessage()               {}
func (*InstallReleaseRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{11} }

func (m *InstallReleaseRequest) GetChart() *hapi_chart3.Chart {
	if m != nil {
		return m.Chart
	}
	return nil
}

func (m *InstallReleaseRequest) GetValues() *hapi_chart.Config {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *InstallReleaseRequest) GetDryRun() bool {
	if m != nil {
		return m.DryRun
	}
	return false
}

func (m *InstallReleaseRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *InstallReleaseRequest) GetDisableHooks() bool {
	if m != nil {
		return m.DisableHooks
	}
	return false
}

func (m *InstallReleaseRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *InstallReleaseRequest) GetReuseName() bool {
	if m != nil {
		return m.ReuseName
	}
	return false
}

func (m *InstallReleaseRequest) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *InstallReleaseRequest) GetWait() bool {
	if m != nil {
		return m.Wait
	}
	return false
}

// InstallReleaseResponse is the response from a release installation.
type InstallReleaseResponse struct {
	Release *hapi_release5.Release `protobuf:"bytes,1,opt,name=release" json:"release,omitempty"`
}

func (m *InstallReleaseResponse) Reset()                    { *m = InstallReleaseResponse{} }
func (m *InstallReleaseResponse) String() string            { return proto.CompactTextString(m) }
func (*InstallReleaseResponse) ProtoMessage()               {}
func (*InstallReleaseResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{12} }

func (m *InstallReleaseResponse) GetRelease() *hapi_release5.Release {
	if m != nil {
		return m.Release
	}
	return nil
}

// UninstallReleaseRequest represents a request to uninstall a named release.
type UninstallReleaseRequest struct {
	// Name is the name of the release to delete.
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// DisableHooks causes the server to skip running any hooks for the uninstall.
	DisableHooks bool `protobuf:"varint,2,opt,name=disable_hooks,json=disableHooks" json:"disable_hooks,omitempty"`
	// Purge removes the release from the store and make its name free for later use.
	Purge bool `protobuf:"varint,3,opt,name=purge" json:"purge,omitempty"`
	// timeout specifies the max amount of time any kubernetes client command can run.
	Timeout int64 `protobuf:"varint,4,opt,name=timeout" json:"timeout,omitempty"`
}

func (m *UninstallReleaseRequest) Reset()                    { *m = UninstallReleaseRequest{} }
func (m *UninstallReleaseRequest) String() string            { return proto.CompactTextString(m) }
func (*UninstallReleaseRequest) ProtoMessage()               {}
func (*UninstallReleaseRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{13} }

func (m *UninstallReleaseRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UninstallReleaseRequest) GetDisableHooks() bool {
	if m != nil {
		return m.DisableHooks
	}
	return false
}

func (m *UninstallReleaseRequest) GetPurge() bool {
	if m != nil {
		return m.Purge
	}
	return false
}

func (m *UninstallReleaseRequest) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

// UninstallReleaseResponse represents a successful response to an uninstall request.
type UninstallReleaseResponse struct {
	// Release is the release that was marked deleted.
	Release *hapi_release5.Release `protobuf:"bytes,1,opt,name=release" json:"release,omitempty"`
	// Info is an uninstall message
	Info string `protobuf:"bytes,2,opt,name=info" json:"info,omitempty"`
}

func (m *UninstallReleaseResponse) Reset()                    { *m = UninstallReleaseResponse{} }
func (m *UninstallReleaseResponse) String() string            { return proto.CompactTextString(m) }
func (*UninstallReleaseResponse) ProtoMessage()               {}
func (*UninstallReleaseResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{14} }

func (m *UninstallReleaseResponse) GetRelease() *hapi_release5.Release {
	if m != nil {
		return m.Release
	}
	return nil
}

func (m *UninstallReleaseResponse) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

// GetVersionRequest requests for version information.
type GetVersionRequest struct {
}

func (m *GetVersionRequest) Reset()                    { *m = GetVersionRequest{} }
func (m *GetVersionRequest) String() string            { return proto.CompactTextString(m) }
func (*GetVersionRequest) ProtoMessage()               {}
func (*GetVersionRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{15} }

type GetVersionResponse struct {
	Version *hapi_version.Version `protobuf:"bytes,1,opt,name=Version,json=version" json:"Version,omitempty"`
}

func (m *GetVersionResponse) Reset()                    { *m = GetVersionResponse{} }
func (m *GetVersionResponse) String() string            { return proto.CompactTextString(m) }
func (*GetVersionResponse) ProtoMessage()               {}
func (*GetVersionResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{16} }

func (m *GetVersionResponse) GetVersion() *hapi_version.Version {
	if m != nil {
		return m.Version
	}
	return nil
}

// GetHistoryRequest requests a release's history.
type GetHistoryRequest struct {
	// The name of the release.
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// The maximum number of releases to include.
	Max int32 `protobuf:"varint,2,opt,name=max" json:"max,omitempty"`
}

func (m *GetHistoryRequest) Reset()                    { *m = GetHistoryRequest{} }
func (m *GetHistoryRequest) String() string            { return proto.CompactTextString(m) }
func (*GetHistoryRequest) ProtoMessage()               {}
func (*GetHistoryRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{17} }

func (m *GetHistoryRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetHistoryRequest) GetMax() int32 {
	if m != nil {
		return m.Max
	}
	return 0
}

// GetHistoryResponse is received in response to a GetHistory rpc.
type GetHistoryResponse struct {
	Releases []*hapi_release5.Release `protobuf:"bytes,1,rep,name=releases" json:"releases,omitempty"`
}

func (m *GetHistoryResponse) Reset()                    { *m = GetHistoryResponse{} }
func (m *GetHistoryResponse) String() string            { return proto.CompactTextString(m) }
func (*GetHistoryResponse) ProtoMessage()               {}
func (*GetHistoryResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{18} }

func (m *GetHistoryResponse) GetReleases() []*hapi_release5.Release {
	if m != nil {
		return m.Releases
	}
	return nil
}

// TestReleaseRequest is a request to get the status of a release.
type TestReleaseRequest struct {
	// Name is the name of the release
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// timeout specifies the max amount of time any kubernetes client command can run.
	Timeout int64 `protobuf:"varint,2,opt,name=timeout" json:"timeout,omitempty"`
	// cleanup specifies whether or not to attempt pod deletion after test completes
	Cleanup bool `protobuf:"varint,3,opt,name=cleanup" json:"cleanup,omitempty"`
}

func (m *TestReleaseRequest) Reset()                    { *m = TestReleaseRequest{} }
func (m *TestReleaseRequest) String() string            { return proto.CompactTextString(m) }
func (*TestReleaseRequest) ProtoMessage()               {}
func (*TestReleaseRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{19} }

func (m *TestReleaseRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TestReleaseRequest) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *TestReleaseRequest) GetCleanup() bool {
	if m != nil {
		return m.Cleanup
	}
	return false
}

// TestReleaseResponse represents a message from executing a test
type TestReleaseResponse struct {
	Msg    string                       `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
	Status hapi_release1.TestRun_Status `protobuf:"varint,2,opt,name=status,enum=hapi.release.TestRun_Status" json:"status,omitempty"`
}

func (m *TestReleaseResponse) Reset()                    { *m = TestReleaseResponse{} }
func (m *TestReleaseResponse) String() string            { return proto.CompactTextString(m) }
func (*TestReleaseResponse) ProtoMessage()               {}
func (*TestReleaseResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{20} }

func (m *TestReleaseResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *TestReleaseResponse) GetStatus() hapi_release1.TestRun_Status {
	if m != nil {
		return m.Status
	}
	return hapi_release1.TestRun_UNKNOWN
}

func init() {
	proto.RegisterType((*ListReleasesRequest)(nil), "appscode.seed.app.v1beta1.ListReleasesRequest")
	proto.RegisterType((*ListSort)(nil), "appscode.seed.app.v1beta1.ListSort")
	proto.RegisterType((*ListReleasesResponse)(nil), "appscode.seed.app.v1beta1.ListReleasesResponse")
	proto.RegisterType((*GetReleaseStatusRequest)(nil), "appscode.seed.app.v1beta1.GetReleaseStatusRequest")
	proto.RegisterType((*GetReleaseStatusResponse)(nil), "appscode.seed.app.v1beta1.GetReleaseStatusResponse")
	proto.RegisterType((*GetReleaseContentRequest)(nil), "appscode.seed.app.v1beta1.GetReleaseContentRequest")
	proto.RegisterType((*GetReleaseContentResponse)(nil), "appscode.seed.app.v1beta1.GetReleaseContentResponse")
	proto.RegisterType((*UpdateReleaseRequest)(nil), "appscode.seed.app.v1beta1.UpdateReleaseRequest")
	proto.RegisterType((*UpdateReleaseResponse)(nil), "appscode.seed.app.v1beta1.UpdateReleaseResponse")
	proto.RegisterType((*RollbackReleaseRequest)(nil), "appscode.seed.app.v1beta1.RollbackReleaseRequest")
	proto.RegisterType((*RollbackReleaseResponse)(nil), "appscode.seed.app.v1beta1.RollbackReleaseResponse")
	proto.RegisterType((*InstallReleaseRequest)(nil), "appscode.seed.app.v1beta1.InstallReleaseRequest")
	proto.RegisterType((*InstallReleaseResponse)(nil), "appscode.seed.app.v1beta1.InstallReleaseResponse")
	proto.RegisterType((*UninstallReleaseRequest)(nil), "appscode.seed.app.v1beta1.UninstallReleaseRequest")
	proto.RegisterType((*UninstallReleaseResponse)(nil), "appscode.seed.app.v1beta1.UninstallReleaseResponse")
	proto.RegisterType((*GetVersionRequest)(nil), "appscode.seed.app.v1beta1.GetVersionRequest")
	proto.RegisterType((*GetVersionResponse)(nil), "appscode.seed.app.v1beta1.GetVersionResponse")
	proto.RegisterType((*GetHistoryRequest)(nil), "appscode.seed.app.v1beta1.GetHistoryRequest")
	proto.RegisterType((*GetHistoryResponse)(nil), "appscode.seed.app.v1beta1.GetHistoryResponse")
	proto.RegisterType((*TestReleaseRequest)(nil), "appscode.seed.app.v1beta1.TestReleaseRequest")
	proto.RegisterType((*TestReleaseResponse)(nil), "appscode.seed.app.v1beta1.TestReleaseResponse")
	proto.RegisterEnum("appscode.seed.app.v1beta1.ListSort_SortBy", ListSort_SortBy_name, ListSort_SortBy_value)
	proto.RegisterEnum("appscode.seed.app.v1beta1.ListSort_SortOrder", ListSort_SortOrder_name, ListSort_SortOrder_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ReleaseService service

type ReleaseServiceClient interface {
	// ListReleases retrieves release history.
	// TODO: Allow filtering the set of releases by
	// release status. By default, ListAllReleases returns the releases who
	// current status is "Active".
	ListReleases(ctx context.Context, in *ListReleasesRequest, opts ...grpc.CallOption) (ReleaseService_ListReleasesClient, error)
	// GetReleasesStatus retrieves status information for the specified release.
	GetReleaseStatus(ctx context.Context, in *GetReleaseStatusRequest, opts ...grpc.CallOption) (*GetReleaseStatusResponse, error)
	// GetReleaseContent retrieves the release content (chart + value) for the specified release.
	GetReleaseContent(ctx context.Context, in *GetReleaseContentRequest, opts ...grpc.CallOption) (*GetReleaseContentResponse, error)
	// UpdateRelease updates release content.
	UpdateRelease(ctx context.Context, in *UpdateReleaseRequest, opts ...grpc.CallOption) (*UpdateReleaseResponse, error)
	// InstallRelease requests installation of a chart as a new release.
	InstallRelease(ctx context.Context, in *InstallReleaseRequest, opts ...grpc.CallOption) (*InstallReleaseResponse, error)
	// UninstallRelease requests deletion of a named release.
	UninstallRelease(ctx context.Context, in *UninstallReleaseRequest, opts ...grpc.CallOption) (*UninstallReleaseResponse, error)
	// GetVersion returns the current version of the server.
	GetVersion(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*GetVersionResponse, error)
	// RollbackRelease rolls back a release to a previous version.
	RollbackRelease(ctx context.Context, in *RollbackReleaseRequest, opts ...grpc.CallOption) (*RollbackReleaseResponse, error)
	// ReleaseHistory retrieves a releasse's history.
	GetHistory(ctx context.Context, in *GetHistoryRequest, opts ...grpc.CallOption) (*GetHistoryResponse, error)
	// RunReleaseTest executes the tests defined of a named release
	RunReleaseTest(ctx context.Context, in *TestReleaseRequest, opts ...grpc.CallOption) (ReleaseService_RunReleaseTestClient, error)
}

type releaseServiceClient struct {
	cc *grpc.ClientConn
}

func NewReleaseServiceClient(cc *grpc.ClientConn) ReleaseServiceClient {
	return &releaseServiceClient{cc}
}

func (c *releaseServiceClient) ListReleases(ctx context.Context, in *ListReleasesRequest, opts ...grpc.CallOption) (ReleaseService_ListReleasesClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_ReleaseService_serviceDesc.Streams[0], c.cc, "/appscode.seed.app.v1beta1.ReleaseService/ListReleases", opts...)
	if err != nil {
		return nil, err
	}
	x := &releaseServiceListReleasesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ReleaseService_ListReleasesClient interface {
	Recv() (*ListReleasesResponse, error)
	grpc.ClientStream
}

type releaseServiceListReleasesClient struct {
	grpc.ClientStream
}

func (x *releaseServiceListReleasesClient) Recv() (*ListReleasesResponse, error) {
	m := new(ListReleasesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *releaseServiceClient) GetReleaseStatus(ctx context.Context, in *GetReleaseStatusRequest, opts ...grpc.CallOption) (*GetReleaseStatusResponse, error) {
	out := new(GetReleaseStatusResponse)
	err := grpc.Invoke(ctx, "/appscode.seed.app.v1beta1.ReleaseService/GetReleaseStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *releaseServiceClient) GetReleaseContent(ctx context.Context, in *GetReleaseContentRequest, opts ...grpc.CallOption) (*GetReleaseContentResponse, error) {
	out := new(GetReleaseContentResponse)
	err := grpc.Invoke(ctx, "/appscode.seed.app.v1beta1.ReleaseService/GetReleaseContent", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *releaseServiceClient) UpdateRelease(ctx context.Context, in *UpdateReleaseRequest, opts ...grpc.CallOption) (*UpdateReleaseResponse, error) {
	out := new(UpdateReleaseResponse)
	err := grpc.Invoke(ctx, "/appscode.seed.app.v1beta1.ReleaseService/UpdateRelease", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *releaseServiceClient) InstallRelease(ctx context.Context, in *InstallReleaseRequest, opts ...grpc.CallOption) (*InstallReleaseResponse, error) {
	out := new(InstallReleaseResponse)
	err := grpc.Invoke(ctx, "/appscode.seed.app.v1beta1.ReleaseService/InstallRelease", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *releaseServiceClient) UninstallRelease(ctx context.Context, in *UninstallReleaseRequest, opts ...grpc.CallOption) (*UninstallReleaseResponse, error) {
	out := new(UninstallReleaseResponse)
	err := grpc.Invoke(ctx, "/appscode.seed.app.v1beta1.ReleaseService/UninstallRelease", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *releaseServiceClient) GetVersion(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*GetVersionResponse, error) {
	out := new(GetVersionResponse)
	err := grpc.Invoke(ctx, "/appscode.seed.app.v1beta1.ReleaseService/GetVersion", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *releaseServiceClient) RollbackRelease(ctx context.Context, in *RollbackReleaseRequest, opts ...grpc.CallOption) (*RollbackReleaseResponse, error) {
	out := new(RollbackReleaseResponse)
	err := grpc.Invoke(ctx, "/appscode.seed.app.v1beta1.ReleaseService/RollbackRelease", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *releaseServiceClient) GetHistory(ctx context.Context, in *GetHistoryRequest, opts ...grpc.CallOption) (*GetHistoryResponse, error) {
	out := new(GetHistoryResponse)
	err := grpc.Invoke(ctx, "/appscode.seed.app.v1beta1.ReleaseService/GetHistory", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *releaseServiceClient) RunReleaseTest(ctx context.Context, in *TestReleaseRequest, opts ...grpc.CallOption) (ReleaseService_RunReleaseTestClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_ReleaseService_serviceDesc.Streams[1], c.cc, "/appscode.seed.app.v1beta1.ReleaseService/RunReleaseTest", opts...)
	if err != nil {
		return nil, err
	}
	x := &releaseServiceRunReleaseTestClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ReleaseService_RunReleaseTestClient interface {
	Recv() (*TestReleaseResponse, error)
	grpc.ClientStream
}

type releaseServiceRunReleaseTestClient struct {
	grpc.ClientStream
}

func (x *releaseServiceRunReleaseTestClient) Recv() (*TestReleaseResponse, error) {
	m := new(TestReleaseResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for ReleaseService service

type ReleaseServiceServer interface {
	// ListReleases retrieves release history.
	// TODO: Allow filtering the set of releases by
	// release status. By default, ListAllReleases returns the releases who
	// current status is "Active".
	ListReleases(*ListReleasesRequest, ReleaseService_ListReleasesServer) error
	// GetReleasesStatus retrieves status information for the specified release.
	GetReleaseStatus(context.Context, *GetReleaseStatusRequest) (*GetReleaseStatusResponse, error)
	// GetReleaseContent retrieves the release content (chart + value) for the specified release.
	GetReleaseContent(context.Context, *GetReleaseContentRequest) (*GetReleaseContentResponse, error)
	// UpdateRelease updates release content.
	UpdateRelease(context.Context, *UpdateReleaseRequest) (*UpdateReleaseResponse, error)
	// InstallRelease requests installation of a chart as a new release.
	InstallRelease(context.Context, *InstallReleaseRequest) (*InstallReleaseResponse, error)
	// UninstallRelease requests deletion of a named release.
	UninstallRelease(context.Context, *UninstallReleaseRequest) (*UninstallReleaseResponse, error)
	// GetVersion returns the current version of the server.
	GetVersion(context.Context, *GetVersionRequest) (*GetVersionResponse, error)
	// RollbackRelease rolls back a release to a previous version.
	RollbackRelease(context.Context, *RollbackReleaseRequest) (*RollbackReleaseResponse, error)
	// ReleaseHistory retrieves a releasse's history.
	GetHistory(context.Context, *GetHistoryRequest) (*GetHistoryResponse, error)
	// RunReleaseTest executes the tests defined of a named release
	RunReleaseTest(*TestReleaseRequest, ReleaseService_RunReleaseTestServer) error
}

func RegisterReleaseServiceServer(s *grpc.Server, srv ReleaseServiceServer) {
	s.RegisterService(&_ReleaseService_serviceDesc, srv)
}

func _ReleaseService_ListReleases_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListReleasesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ReleaseServiceServer).ListReleases(m, &releaseServiceListReleasesServer{stream})
}

type ReleaseService_ListReleasesServer interface {
	Send(*ListReleasesResponse) error
	grpc.ServerStream
}

type releaseServiceListReleasesServer struct {
	grpc.ServerStream
}

func (x *releaseServiceListReleasesServer) Send(m *ListReleasesResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _ReleaseService_GetReleaseStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReleaseStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReleaseServiceServer).GetReleaseStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appscode.seed.app.v1beta1.ReleaseService/GetReleaseStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReleaseServiceServer).GetReleaseStatus(ctx, req.(*GetReleaseStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReleaseService_GetReleaseContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReleaseContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReleaseServiceServer).GetReleaseContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appscode.seed.app.v1beta1.ReleaseService/GetReleaseContent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReleaseServiceServer).GetReleaseContent(ctx, req.(*GetReleaseContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReleaseService_UpdateRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReleaseServiceServer).UpdateRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appscode.seed.app.v1beta1.ReleaseService/UpdateRelease",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReleaseServiceServer).UpdateRelease(ctx, req.(*UpdateReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReleaseService_InstallRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstallReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReleaseServiceServer).InstallRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appscode.seed.app.v1beta1.ReleaseService/InstallRelease",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReleaseServiceServer).InstallRelease(ctx, req.(*InstallReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReleaseService_UninstallRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UninstallReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReleaseServiceServer).UninstallRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appscode.seed.app.v1beta1.ReleaseService/UninstallRelease",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReleaseServiceServer).UninstallRelease(ctx, req.(*UninstallReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReleaseService_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReleaseServiceServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appscode.seed.app.v1beta1.ReleaseService/GetVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReleaseServiceServer).GetVersion(ctx, req.(*GetVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReleaseService_RollbackRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReleaseServiceServer).RollbackRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appscode.seed.app.v1beta1.ReleaseService/RollbackRelease",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReleaseServiceServer).RollbackRelease(ctx, req.(*RollbackReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReleaseService_GetHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReleaseServiceServer).GetHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appscode.seed.app.v1beta1.ReleaseService/GetHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReleaseServiceServer).GetHistory(ctx, req.(*GetHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReleaseService_RunReleaseTest_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TestReleaseRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ReleaseServiceServer).RunReleaseTest(m, &releaseServiceRunReleaseTestServer{stream})
}

type ReleaseService_RunReleaseTestServer interface {
	Send(*TestReleaseResponse) error
	grpc.ServerStream
}

type releaseServiceRunReleaseTestServer struct {
	grpc.ServerStream
}

func (x *releaseServiceRunReleaseTestServer) Send(m *TestReleaseResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _ReleaseService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "appscode.seed.app.v1beta1.ReleaseService",
	HandlerType: (*ReleaseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetReleaseStatus",
			Handler:    _ReleaseService_GetReleaseStatus_Handler,
		},
		{
			MethodName: "GetReleaseContent",
			Handler:    _ReleaseService_GetReleaseContent_Handler,
		},
		{
			MethodName: "UpdateRelease",
			Handler:    _ReleaseService_UpdateRelease_Handler,
		},
		{
			MethodName: "InstallRelease",
			Handler:    _ReleaseService_InstallRelease_Handler,
		},
		{
			MethodName: "UninstallRelease",
			Handler:    _ReleaseService_UninstallRelease_Handler,
		},
		{
			MethodName: "GetVersion",
			Handler:    _ReleaseService_GetVersion_Handler,
		},
		{
			MethodName: "RollbackRelease",
			Handler:    _ReleaseService_RollbackRelease_Handler,
		},
		{
			MethodName: "GetHistory",
			Handler:    _ReleaseService_GetHistory_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListReleases",
			Handler:       _ReleaseService_ListReleases_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "RunReleaseTest",
			Handler:       _ReleaseService_RunReleaseTest_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "tiller.proto",
}

func init() { proto.RegisterFile("tiller.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 1313 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x57, 0xcd, 0x6e, 0xdb, 0xc6,
	0x13, 0x37, 0xf5, 0xad, 0xb1, 0xe3, 0xbf, 0xb2, 0x71, 0x6c, 0x9a, 0xff, 0x24, 0x70, 0x59, 0xa0,
	0x35, 0x82, 0x46, 0x8a, 0x95, 0x5c, 0x8a, 0xf6, 0xe2, 0x28, 0x82, 0x9d, 0xd6, 0x75, 0x02, 0x2a,
	0x49, 0x81, 0xa2, 0xad, 0x40, 0x4b, 0x2b, 0x87, 0x08, 0xc5, 0x65, 0xb9, 0x4b, 0x27, 0x2e, 0x10,
	0xa0, 0xc8, 0xad, 0xe7, 0x3e, 0x45, 0x2f, 0xbd, 0xf5, 0x25, 0x7a, 0xed, 0x23, 0x34, 0x8f, 0xd1,
	0x43, 0xb1, 0x5f, 0x34, 0x57, 0x96, 0x64, 0xd9, 0x17, 0x91, 0xb3, 0xf3, 0xfd, 0x9b, 0xe1, 0xec,
	0x08, 0x56, 0x58, 0x10, 0x86, 0x38, 0x69, 0xc6, 0x09, 0x61, 0x04, 0x6d, 0xfa, 0x71, 0x4c, 0x07,
	0x64, 0x88, 0x9b, 0x14, 0xe3, 0x61, 0xd3, 0x8f, 0xe3, 0xe6, 0xc9, 0xce, 0x11, 0x66, 0xfe, 0x8e,
	0xb3, 0xfe, 0xca, 0x8f, 0x83, 0xd6, 0xe0, 0x95, 0x9f, 0x30, 0xf9, 0x2b, 0x55, 0x9c, 0x8d, 0xfc,
	0x39, 0x89, 0x46, 0xc1, 0xb1, 0x62, 0x38, 0x82, 0x91, 0xe0, 0x10, 0xfb, 0x14, 0xeb, 0xa7, 0xa1,
	0xa4, 0x79, 0x41, 0x34, 0x22, 0x8a, 0xf1, 0x7f, 0x83, 0xc1, 0x30, 0x65, 0xfd, 0x24, 0x8d, 0x14,
	0x73, 0xd3, 0x60, 0x52, 0xe6, 0xb3, 0x94, 0x1a, 0xce, 0x4e, 0x70, 0x42, 0x03, 0x12, 0xe9, 0xa7,
	0xe2, 0xdd, 0x3a, 0x26, 0xe4, 0x38, 0xc4, 0x2d, 0x2e, 0xe1, 0x47, 0x11, 0x61, 0x3e, 0x0b, 0x48,
	0xa4, 0x35, 0xef, 0xe8, 0x94, 0xa7, 0xf3, 0xdd, 0xbf, 0x0a, 0x70, 0xe3, 0x20, 0xa0, 0xcc, 0x93,
	0x6e, 0xa9, 0x87, 0x7f, 0x4a, 0x31, 0x65, 0x68, 0x0d, 0xca, 0x61, 0x30, 0x0e, 0x98, 0x6d, 0x6d,
	0x59, 0xdb, 0x45, 0x4f, 0x12, 0x68, 0x1d, 0x2a, 0x64, 0x34, 0xa2, 0x98, 0xd9, 0x85, 0x2d, 0x6b,
	0xbb, 0xee, 0x29, 0x0a, 0x75, 0xa0, 0x4a, 0x49, 0xc2, 0xfa, 0x47, 0xa7, 0x76, 0x71, 0xcb, 0xda,
	0x5e, 0x6d, 0xdf, 0x6d, 0xce, 0x84, 0xba, 0xc9, 0xdd, 0xf5, 0x48, 0xc2, 0x9a, 0xfc, 0xe7, 0xd1,
	0xa9, 0x57, 0xa1, 0xe2, 0xc9, 0x8d, 0x8f, 0x82, 0x90, 0xe1, 0xc4, 0x2e, 0x49, 0xe3, 0x92, 0x42,
	0x07, 0x00, 0xc2, 0x38, 0x49, 0x86, 0x38, 0xb1, 0xcb, 0xc2, 0xfe, 0xbd, 0x45, 0xed, 0x3f, 0xe5,
	0x4a, 0x5e, 0x9d, 0xea, 0x57, 0xf4, 0x25, 0xac, 0x48, 0x68, 0xfb, 0x5c, 0x9b, 0xda, 0x95, 0xad,
	0xe2, 0xf6, 0x6a, 0x7b, 0xb3, 0xc9, 0x11, 0x6e, 0xea, 0x32, 0xf6, 0x24, 0xf8, 0x1d, 0x32, 0xc4,
	0xde, 0xb2, 0x14, 0xe7, 0xef, 0x14, 0xdd, 0x82, 0x7a, 0xe4, 0x8f, 0x31, 0x8d, 0xfd, 0x01, 0xb6,
	0xab, 0x22, 0xcc, 0xb3, 0x03, 0xf7, 0x47, 0xa8, 0x69, 0xe7, 0x6e, 0x1b, 0x2a, 0x32, 0x3f, 0xb4,
	0x0c, 0xd5, 0x17, 0x87, 0x5f, 0x1f, 0x3e, 0xfd, 0xf6, 0xb0, 0xb1, 0x84, 0x6a, 0x50, 0x3a, 0xdc,
	0xfd, 0xa6, 0xdb, 0xb0, 0xd0, 0x75, 0xb8, 0x76, 0xb0, 0xdb, 0x7b, 0xde, 0xf7, 0xba, 0x07, 0xdd,
	0xdd, 0x5e, 0xf7, 0x71, 0xa3, 0xe0, 0xde, 0x81, 0x7a, 0x16, 0x33, 0xaa, 0x42, 0x71, 0xb7, 0xd7,
	0x91, 0x2a, 0x8f, 0xbb, 0xbd, 0x4e, 0xc3, 0x72, 0x7f, 0xb5, 0x60, 0xcd, 0x2c, 0x16, 0x8d, 0x49,
	0x44, 0x31, 0xaf, 0xd6, 0x80, 0xa4, 0x51, 0x56, 0x2d, 0x41, 0x20, 0x04, 0xa5, 0x08, 0xbf, 0xd5,
	0xb5, 0x12, 0xef, 0x5c, 0x92, 0x11, 0xe6, 0x87, 0xa2, 0x4e, 0x45, 0x4f, 0x12, 0x68, 0x07, 0x6a,
	0x2a, 0x75, 0x6a, 0x97, 0xb6, 0x8a, 0xdb, 0xcb, 0xed, 0x9b, 0x26, 0x20, 0xca, 0xa3, 0x97, 0x89,
	0xb9, 0x7b, 0xb0, 0xb1, 0x87, 0x75, 0x24, 0x12, 0x2f, 0xdd, 0x3b, 0xdc, 0xaf, 0x3f, 0xc6, 0x22,
	0x18, 0xee, 0xd7, 0x1f, 0x63, 0x64, 0x43, 0x55, 0xb5, 0xad, 0x08, 0xa7, 0xec, 0x69, 0xd2, 0x65,
	0x60, 0x9f, 0x37, 0xa4, 0xf2, 0x9a, 0x66, 0xe9, 0x13, 0x28, 0xf1, 0x2f, 0x4a, 0x98, 0x59, 0x6e,
	0x23, 0x33, 0xce, 0x27, 0xd1, 0x88, 0x78, 0x82, 0x6f, 0x96, 0xaa, 0x38, 0x59, 0xaa, 0xfd, 0xbc,
	0xd7, 0x0e, 0x89, 0x18, 0x8e, 0xd8, 0xd5, 0xe2, 0x3f, 0x80, 0xcd, 0x29, 0x96, 0x54, 0x02, 0x2d,
	0xa8, 0xaa, 0xd0, 0x84, 0xb5, 0x99, 0xb8, 0x6a, 0x29, 0xf7, 0x9f, 0x02, 0xac, 0xbd, 0x88, 0x87,
	0x3e, 0xc3, 0x9a, 0x35, 0x27, 0xa8, 0x4f, 0xa1, 0x2c, 0x26, 0x93, 0xc2, 0xe2, 0xba, 0xb4, 0x2d,
	0xc7, 0x57, 0x87, 0xff, 0x7a, 0x92, 0x8f, 0xee, 0x42, 0xe5, 0xc4, 0x0f, 0x53, 0x4c, 0x05, 0x10,
	0x19, 0x6a, 0x4a, 0x52, 0x8c, 0x35, 0x4f, 0x49, 0xa0, 0x0d, 0xa8, 0x0e, 0x93, 0x53, 0x3e, 0x97,
	0xc4, 0x77, 0x58, 0xf3, 0x2a, 0xc3, 0xe4, 0xd4, 0x4b, 0x23, 0xf4, 0x31, 0x5c, 0x1b, 0x06, 0xd4,
	0x3f, 0x0a, 0x71, 0xff, 0x15, 0x21, 0xaf, 0xa9, 0xf8, 0x14, 0x6b, 0xde, 0x8a, 0x3a, 0xdc, 0xe7,
	0x67, 0xc8, 0xe1, 0x9d, 0x34, 0x48, 0xb0, 0xcf, 0xb0, 0x5d, 0x11, 0xfc, 0x8c, 0xe6, 0x18, 0xb2,
	0x60, 0x8c, 0x49, 0xca, 0xc4, 0xa7, 0x53, 0xf4, 0x34, 0x89, 0x3e, 0x82, 0x95, 0x04, 0x53, 0xcc,
	0xfa, 0x2a, 0xca, 0x9a, 0xd0, 0x5c, 0x16, 0x67, 0x2f, 0x65, 0x58, 0x08, 0x4a, 0x6f, 0xfc, 0x80,
	0xd9, 0x75, 0xc1, 0x12, 0xef, 0x52, 0x2d, 0xa5, 0x58, 0xab, 0x81, 0x56, 0x4b, 0x29, 0x56, 0x6a,
	0x6b, 0x50, 0x1e, 0x91, 0x64, 0x80, 0xed, 0x65, 0xc1, 0x93, 0x84, 0xbb, 0x0f, 0x37, 0x27, 0x40,
	0xbe, 0x6a, 0xbd, 0x3e, 0x58, 0xb0, 0xee, 0x91, 0x30, 0x3c, 0xf2, 0x07, 0xaf, 0x17, 0xa8, 0x58,
	0x0e, 0xdc, 0xc2, 0x7c, 0x70, 0x8b, 0x53, 0xc0, 0xcd, 0x35, 0x61, 0xc9, 0x68, 0x42, 0x03, 0xf6,
	0xf2, 0x6c, 0xd8, 0x2b, 0x26, 0xec, 0x1a, 0xd3, 0x6a, 0x0e, 0xd3, 0x0c, 0xb0, 0x5a, 0x1e, 0xb0,
	0xaf, 0x60, 0xe3, 0x5c, 0x96, 0x57, 0x85, 0xec, 0xf7, 0x02, 0xdc, 0x7c, 0x12, 0x51, 0xe6, 0x87,
	0xe1, 0x04, 0x62, 0x59, 0x3f, 0x5b, 0x0b, 0xf7, 0x73, 0xe1, 0x32, 0xfd, 0x5c, 0x34, 0x20, 0xd7,
	0xf5, 0x29, 0xe5, 0xea, 0xb3, 0x50, 0x8f, 0x1b, 0x93, 0xa5, 0x32, 0x31, 0x59, 0xd0, 0x6d, 0x00,
	0xd9, 0x94, 0xc2, 0xb8, 0x84, 0xb6, 0x2e, 0x4e, 0x0e, 0xd5, 0x20, 0xd1, 0xd5, 0xa8, 0x4d, 0xaf,
	0x46, 0xae, 0xc3, 0xdd, 0x27, 0xb0, 0x3e, 0x09, 0xd5, 0x55, 0x61, 0x7f, 0x6f, 0xc1, 0xc6, 0x8b,
	0x28, 0x98, 0x0a, 0xfc, 0xb4, 0x56, 0x3d, 0x07, 0x45, 0x61, 0x0a, 0x14, 0x6b, 0x50, 0x8e, 0xd3,
	0xe4, 0x18, 0x2b, 0x68, 0x25, 0x91, 0xcf, 0xb1, 0x64, 0xe4, 0xe8, 0xf6, 0xc1, 0x3e, 0x1f, 0xc3,
	0x15, 0x33, 0xe2, 0x51, 0x67, 0x37, 0x41, 0x5d, 0x4e, 0x7d, 0xf7, 0x06, 0x5c, 0xdf, 0xc3, 0xec,
	0xa5, 0xfc, 0x2c, 0x54, 0x7a, 0x6e, 0x17, 0x50, 0xfe, 0xf0, 0xcc, 0x9f, 0x3a, 0x32, 0xfd, 0xe9,
	0xf5, 0x4a, 0xcb, 0x67, 0x93, 0xfe, 0x73, 0x61, 0x7b, 0x3f, 0xa0, 0x8c, 0x24, 0xa7, 0xf3, 0xa0,
	0x6b, 0x40, 0x71, 0xec, 0xbf, 0x55, 0x17, 0x05, 0x7f, 0x75, 0xf7, 0x44, 0x04, 0x99, 0xaa, 0x8a,
	0x20, 0x7f, 0xed, 0x5a, 0x8b, 0x5d, 0xbb, 0xdf, 0x03, 0x7a, 0x8e, 0xb3, 0x0d, 0xe0, 0x82, 0x1b,
	0x4b, 0x17, 0xa1, 0x60, 0x36, 0x9a, 0x0d, 0xd5, 0x41, 0x88, 0xfd, 0x28, 0x8d, 0x55, 0xd9, 0x34,
	0xe9, 0xfe, 0x00, 0x37, 0x0c, 0xeb, 0x2a, 0x4e, 0x9e, 0x0f, 0x3d, 0x56, 0xd6, 0xf9, 0x2b, 0x7a,
	0x08, 0x15, 0xb9, 0x16, 0x09, 0xdb, 0xab, 0xed, 0x5b, 0x66, 0xdc, 0xc2, 0x48, 0x1a, 0xa9, 0x3d,
	0xca, 0x53, 0xb2, 0xed, 0x7f, 0xeb, 0xb0, 0xaa, 0x2f, 0x7a, 0x9c, 0x9c, 0x04, 0x03, 0x8c, 0xfe,
	0xb0, 0x60, 0x25, 0xbf, 0xd2, 0xa0, 0xe6, 0x05, 0x9b, 0xdd, 0xc4, 0xa2, 0xea, 0xb4, 0x16, 0x96,
	0x97, 0xc9, 0xb8, 0x5f, 0xbc, 0xff, 0xd3, 0x2e, 0xd4, 0xac, 0xf7, 0x7f, 0x7f, 0xf8, 0xad, 0xd0,
	0x42, 0xf7, 0x5a, 0x7d, 0x63, 0x43, 0xe6, 0x36, 0x5a, 0x4a, 0xbf, 0xc5, 0x39, 0xad, 0x30, 0xa0,
	0x4c, 0xc3, 0x7f, 0xdf, 0x42, 0xef, 0xa0, 0x31, 0xb9, 0xae, 0xa0, 0xf6, 0x9c, 0x18, 0x66, 0x2c,
	0x49, 0xce, 0x83, 0x4b, 0xe9, 0xa8, 0xd8, 0x97, 0xd0, 0x2f, 0x96, 0x68, 0x42, 0x73, 0xdd, 0x40,
	0x8b, 0x19, 0x33, 0xd7, 0x1c, 0xe7, 0xe1, 0xe5, 0x94, 0xb2, 0x10, 0x18, 0x5c, 0x33, 0x2e, 0x4f,
	0x34, 0xaf, 0x04, 0xd3, 0x76, 0x19, 0xe7, 0xfe, 0xe2, 0x0a, 0x99, 0xd7, 0x37, 0xb0, 0x6a, 0x4e,
	0x42, 0x34, 0xcf, 0xca, 0xd4, 0xfb, 0xc5, 0xd9, 0xb9, 0x84, 0x46, 0xe6, 0xf8, 0x1d, 0x34, 0x26,
	0x47, 0xd6, 0xdc, 0x82, 0xcf, 0x98, 0xb1, 0x73, 0x0b, 0x3e, 0x6b, 0x26, 0xba, 0x4b, 0xe8, 0x35,
	0xc0, 0xd9, 0xec, 0x42, 0x9f, 0xcd, 0xaf, 0x99, 0x39, 0xf7, 0x9c, 0x7b, 0x0b, 0x4a, 0x67, 0xce,
	0x7e, 0x86, 0xff, 0x4d, 0x5c, 0xf3, 0x68, 0x1e, 0x66, 0xd3, 0x17, 0x1f, 0xa7, 0x7d, 0x19, 0x95,
	0x89, 0x44, 0xd5, 0x88, 0xbc, 0x28, 0x51, 0x73, 0x08, 0x5f, 0x94, 0xe8, 0xc4, 0xdc, 0x75, 0x97,
	0x10, 0x85, 0x55, 0x2f, 0x8d, 0x54, 0x10, 0x7c, 0x5a, 0xa1, 0x79, 0x26, 0xce, 0x4f, 0x5c, 0xa7,
	0xb9, 0xa8, 0xb8, 0x76, 0x79, 0xdf, 0x7a, 0xf4, 0x10, 0x6e, 0x0f, 0xc8, 0x78, 0xb6, 0xe2, 0xa3,
	0xda, 0x6e, 0x1c, 0x3f, 0xe3, 0x7f, 0xcb, 0x9f, 0x59, 0xdf, 0x55, 0xd5, 0xe1, 0x51, 0x45, 0xfc,
	0x51, 0x7f, 0xf0, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0b, 0xad, 0xbf, 0xfd, 0xcb, 0x10, 0x00,
	0x00,
}
