// Code generated by protoc-gen-grpc-gateway-cors
// source: tiller.proto
// DO NOT EDIT!

/*
Package v1beta1 is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package v1beta1

import "github.com/grpc-ecosystem/grpc-gateway/runtime"

// ExportReleaseServiceCorsPatterns returns an array of grpc gatway mux patterns for
// ReleaseService service to enable CORS.
func ExportReleaseServiceCorsPatterns() []runtime.Pattern {
	return []runtime.Pattern{}
}
