// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tiller.proto

package v2

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/grpc-ecosystem/grpc-gateway/third_party/appscodeapis/appscode/api"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import chart "k8s.io/helm/pkg/proto/hapi/chart"
import release "k8s.io/helm/pkg/proto/hapi/release"
import version "k8s.io/helm/pkg/proto/hapi/version"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// SortBy defines sort operations.
type ListSort_SortBy int32

const (
	ListSort_UNKNOWN       ListSort_SortBy = 0
	ListSort_NAME          ListSort_SortBy = 1
	ListSort_LAST_RELEASED ListSort_SortBy = 2
)

var ListSort_SortBy_name = map[int32]string{
	0: "UNKNOWN",
	1: "NAME",
	2: "LAST_RELEASED",
}
var ListSort_SortBy_value = map[string]int32{
	"UNKNOWN":       0,
	"NAME":          1,
	"LAST_RELEASED": 2,
}

func (x ListSort_SortBy) String() string {
	return proto.EnumName(ListSort_SortBy_name, int32(x))
}
func (ListSort_SortBy) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_tiller_c329dcad7a585ca8, []int{1, 0}
}

// SortOrder defines sort orders to augment sorting operations.
type ListSort_SortOrder int32

const (
	ListSort_ASC  ListSort_SortOrder = 0
	ListSort_DESC ListSort_SortOrder = 1
)

var ListSort_SortOrder_name = map[int32]string{
	0: "ASC",
	1: "DESC",
}
var ListSort_SortOrder_value = map[string]int32{
	"ASC":  0,
	"DESC": 1,
}

func (x ListSort_SortOrder) String() string {
	return proto.EnumName(ListSort_SortOrder_name, int32(x))
}
func (ListSort_SortOrder) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_tiller_c329dcad7a585ca8, []int{1, 1}
}

// SummarizeReleasesRequest requests a list of releases.
//
// Releases can be retrieved in chunks by setting limit and offset.
//
// Releases can be sorted according to a few pre-determined sort stategies.
type SummarizeReleasesRequest struct {
	// Limit is the maximum number of releases to be returned.
	Limit int64 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	// Offset is the last release name that was seen. The next listing
	// operation will start with the name after this one.
	// Example: If list one returns albert, bernie, carl, and sets 'next: dennis'.
	// dennis is the offset. Supplying 'dennis' for the next request should
	// cause the next batch to return a set of results starting with 'dennis'.
	Offset string `protobuf:"bytes,2,opt,name=offset,proto3" json:"offset,omitempty"`
	// SortBy is the sort field that the ListReleases server should sort data before returning.
	SortBy ListSort_SortBy `protobuf:"varint,3,opt,name=sort_by,json=sortBy,proto3,enum=appscode.swift.v2.ListSort_SortBy" json:"sort_by,omitempty"`
	// Filter is a regular expression used to filter which releases should be listed.
	//
	// Anything that matches the regexp will be included in the results.
	Filter string `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	// SortOrder is the ordering directive used for sorting.
	SortOrder ListSort_SortOrder `protobuf:"varint,5,opt,name=sort_order,json=sortOrder,proto3,enum=appscode.swift.v2.ListSort_SortOrder" json:"sort_order,omitempty"`
	// allowed values are UNKNOWN, DEPLOYED, DELETED, SUPERSEDED, FAILED, DELETING
	StatusCodes []string `protobuf:"bytes,6,rep,name=status_codes,json=statusCodes,proto3" json:"status_codes,omitempty"`
	// Namespace is the filter to select releases only from a specific namespace.
	Namespace string `protobuf:"bytes,7,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// if true, list releases with all status codes
	All                  bool     `protobuf:"varint,8,opt,name=all,proto3" json:"all,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SummarizeReleasesRequest) Reset()         { *m = SummarizeReleasesRequest{} }
func (m *SummarizeReleasesRequest) String() string { return proto.CompactTextString(m) }
func (*SummarizeReleasesRequest) ProtoMessage()    {}
func (*SummarizeReleasesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_tiller_c329dcad7a585ca8, []int{0}
}
func (m *SummarizeReleasesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SummarizeReleasesRequest.Unmarshal(m, b)
}
func (m *SummarizeReleasesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SummarizeReleasesRequest.Marshal(b, m, deterministic)
}
func (dst *SummarizeReleasesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SummarizeReleasesRequest.Merge(dst, src)
}
func (m *SummarizeReleasesRequest) XXX_Size() int {
	return xxx_messageInfo_SummarizeReleasesRequest.Size(m)
}
func (m *SummarizeReleasesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SummarizeReleasesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SummarizeReleasesRequest proto.InternalMessageInfo

func (m *SummarizeReleasesRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *SummarizeReleasesRequest) GetOffset() string {
	if m != nil {
		return m.Offset
	}
	return ""
}

func (m *SummarizeReleasesRequest) GetSortBy() ListSort_SortBy {
	if m != nil {
		return m.SortBy
	}
	return ListSort_UNKNOWN
}

func (m *SummarizeReleasesRequest) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

func (m *SummarizeReleasesRequest) GetSortOrder() ListSort_SortOrder {
	if m != nil {
		return m.SortOrder
	}
	return ListSort_ASC
}

func (m *SummarizeReleasesRequest) GetStatusCodes() []string {
	if m != nil {
		return m.StatusCodes
	}
	return nil
}

func (m *SummarizeReleasesRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *SummarizeReleasesRequest) GetAll() bool {
	if m != nil {
		return m.All
	}
	return false
}

// ListSort defines sorting fields on a release list.
type ListSort struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListSort) Reset()         { *m = ListSort{} }
func (m *ListSort) String() string { return proto.CompactTextString(m) }
func (*ListSort) ProtoMessage()    {}
func (*ListSort) Descriptor() ([]byte, []int) {
	return fileDescriptor_tiller_c329dcad7a585ca8, []int{1}
}
func (m *ListSort) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSort.Unmarshal(m, b)
}
func (m *ListSort) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSort.Marshal(b, m, deterministic)
}
func (dst *ListSort) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSort.Merge(dst, src)
}
func (m *ListSort) XXX_Size() int {
	return xxx_messageInfo_ListSort.Size(m)
}
func (m *ListSort) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSort.DiscardUnknown(m)
}

var xxx_messageInfo_ListSort proto.InternalMessageInfo

// @appscode
// SummarizeReleasesResponse is a list of release summaries.
type SummarizeReleasesResponse struct {
	// Count is the expected total number of releases to be returned.
	Count int64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	// Next is the name of the next release. If this is other than an empty
	// string, it means there are more results.
	Next string `protobuf:"bytes,2,opt,name=next,proto3" json:"next,omitempty"`
	// Total is the total number of queryable releases.
	Total                int64             `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Releases             []*ReleaseSummary `protobuf:"bytes,4,rep,name=releases,proto3" json:"releases,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SummarizeReleasesResponse) Reset()         { *m = SummarizeReleasesResponse{} }
func (m *SummarizeReleasesResponse) String() string { return proto.CompactTextString(m) }
func (*SummarizeReleasesResponse) ProtoMessage()    {}
func (*SummarizeReleasesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_tiller_c329dcad7a585ca8, []int{2}
}
func (m *SummarizeReleasesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SummarizeReleasesResponse.Unmarshal(m, b)
}
func (m *SummarizeReleasesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SummarizeReleasesResponse.Marshal(b, m, deterministic)
}
func (dst *SummarizeReleasesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SummarizeReleasesResponse.Merge(dst, src)
}
func (m *SummarizeReleasesResponse) XXX_Size() int {
	return xxx_messageInfo_SummarizeReleasesResponse.Size(m)
}
func (m *SummarizeReleasesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SummarizeReleasesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SummarizeReleasesResponse proto.InternalMessageInfo

func (m *SummarizeReleasesResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *SummarizeReleasesResponse) GetNext() string {
	if m != nil {
		return m.Next
	}
	return ""
}

func (m *SummarizeReleasesResponse) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *SummarizeReleasesResponse) GetReleases() []*ReleaseSummary {
	if m != nil {
		return m.Releases
	}
	return nil
}

// ReleaseSummary summaries a deployment of a chart, together with the chart
// metadata and the variables used to deploy that chart.
type ReleaseSummary struct {
	// Name is the name of the release
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Info provides information about a release
	Info *release.Info `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	// ChartMetadata is the metadata of chart that was released.
	ChartMetadata *chart.Metadata `protobuf:"bytes,3,opt,name=chart_metadata,json=chartMetadata,proto3" json:"chart_metadata,omitempty"`
	// Config is the set of extra Values added to the chart.
	// These values override the default values inside of the chart.
	Config *chart.Config `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	// Version is an int32 which represents the version of the release.
	Version int32 `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	// Namespace is the kubernetes namespace of the release.
	Namespace            string   `protobuf:"bytes,6,opt,name=namespace,proto3" json:"namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReleaseSummary) Reset()         { *m = ReleaseSummary{} }
func (m *ReleaseSummary) String() string { return proto.CompactTextString(m) }
func (*ReleaseSummary) ProtoMessage()    {}
func (*ReleaseSummary) Descriptor() ([]byte, []int) {
	return fileDescriptor_tiller_c329dcad7a585ca8, []int{3}
}
func (m *ReleaseSummary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReleaseSummary.Unmarshal(m, b)
}
func (m *ReleaseSummary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReleaseSummary.Marshal(b, m, deterministic)
}
func (dst *ReleaseSummary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReleaseSummary.Merge(dst, src)
}
func (m *ReleaseSummary) XXX_Size() int {
	return xxx_messageInfo_ReleaseSummary.Size(m)
}
func (m *ReleaseSummary) XXX_DiscardUnknown() {
	xxx_messageInfo_ReleaseSummary.DiscardUnknown(m)
}

var xxx_messageInfo_ReleaseSummary proto.InternalMessageInfo

func (m *ReleaseSummary) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReleaseSummary) GetInfo() *release.Info {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ReleaseSummary) GetChartMetadata() *chart.Metadata {
	if m != nil {
		return m.ChartMetadata
	}
	return nil
}

func (m *ReleaseSummary) GetConfig() *chart.Config {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *ReleaseSummary) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ReleaseSummary) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

// GetReleaseStatusRequest is a request to get the status of a release.
type GetReleaseStatusRequest struct {
	// Name is the name of the release
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Version is the version of the release
	Version              int32    `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetReleaseStatusRequest) Reset()         { *m = GetReleaseStatusRequest{} }
func (m *GetReleaseStatusRequest) String() string { return proto.CompactTextString(m) }
func (*GetReleaseStatusRequest) ProtoMessage()    {}
func (*GetReleaseStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_tiller_c329dcad7a585ca8, []int{4}
}
func (m *GetReleaseStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReleaseStatusRequest.Unmarshal(m, b)
}
func (m *GetReleaseStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReleaseStatusRequest.Marshal(b, m, deterministic)
}
func (dst *GetReleaseStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReleaseStatusRequest.Merge(dst, src)
}
func (m *GetReleaseStatusRequest) XXX_Size() int {
	return xxx_messageInfo_GetReleaseStatusRequest.Size(m)
}
func (m *GetReleaseStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReleaseStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetReleaseStatusRequest proto.InternalMessageInfo

func (m *GetReleaseStatusRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetReleaseStatusRequest) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

// GetReleaseStatusResponse is the response indicating the status of the named release.
type GetReleaseStatusResponse struct {
	// Name is the name of the release.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Info contains information about the release.
	Info *release.Info `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	// Namesapce the release was released into
	Namespace            string   `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetReleaseStatusResponse) Reset()         { *m = GetReleaseStatusResponse{} }
func (m *GetReleaseStatusResponse) String() string { return proto.CompactTextString(m) }
func (*GetReleaseStatusResponse) ProtoMessage()    {}
func (*GetReleaseStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_tiller_c329dcad7a585ca8, []int{5}
}
func (m *GetReleaseStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReleaseStatusResponse.Unmarshal(m, b)
}
func (m *GetReleaseStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReleaseStatusResponse.Marshal(b, m, deterministic)
}
func (dst *GetReleaseStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReleaseStatusResponse.Merge(dst, src)
}
func (m *GetReleaseStatusResponse) XXX_Size() int {
	return xxx_messageInfo_GetReleaseStatusResponse.Size(m)
}
func (m *GetReleaseStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReleaseStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetReleaseStatusResponse proto.InternalMessageInfo

func (m *GetReleaseStatusResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetReleaseStatusResponse) GetInfo() *release.Info {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *GetReleaseStatusResponse) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

// GetReleaseContentRequest is a request to get the contents of a release.
type GetReleaseContentRequest struct {
	// The name of the release
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Version is the version of the release
	Version int32 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	// Format release config and values to JSON string
	FormatValuesAsJson   bool     `protobuf:"varint,3,opt,name=format_values_as_json,json=formatValuesAsJson,proto3" json:"format_values_as_json,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetReleaseContentRequest) Reset()         { *m = GetReleaseContentRequest{} }
func (m *GetReleaseContentRequest) String() string { return proto.CompactTextString(m) }
func (*GetReleaseContentRequest) ProtoMessage()    {}
func (*GetReleaseContentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_tiller_c329dcad7a585ca8, []int{6}
}
func (m *GetReleaseContentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReleaseContentRequest.Unmarshal(m, b)
}
func (m *GetReleaseContentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReleaseContentRequest.Marshal(b, m, deterministic)
}
func (dst *GetReleaseContentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReleaseContentRequest.Merge(dst, src)
}
func (m *GetReleaseContentRequest) XXX_Size() int {
	return xxx_messageInfo_GetReleaseContentRequest.Size(m)
}
func (m *GetReleaseContentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReleaseContentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetReleaseContentRequest proto.InternalMessageInfo

func (m *GetReleaseContentRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetReleaseContentRequest) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *GetReleaseContentRequest) GetFormatValuesAsJson() bool {
	if m != nil {
		return m.FormatValuesAsJson
	}
	return false
}

// GetReleaseContentResponse is a response containing the contents of a release.
type GetReleaseContentResponse struct {
	// The release content
	Release              *release.Release `protobuf:"bytes,1,opt,name=release,proto3" json:"release,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetReleaseContentResponse) Reset()         { *m = GetReleaseContentResponse{} }
func (m *GetReleaseContentResponse) String() string { return proto.CompactTextString(m) }
func (*GetReleaseContentResponse) ProtoMessage()    {}
func (*GetReleaseContentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_tiller_c329dcad7a585ca8, []int{7}
}
func (m *GetReleaseContentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReleaseContentResponse.Unmarshal(m, b)
}
func (m *GetReleaseContentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReleaseContentResponse.Marshal(b, m, deterministic)
}
func (dst *GetReleaseContentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReleaseContentResponse.Merge(dst, src)
}
func (m *GetReleaseContentResponse) XXX_Size() int {
	return xxx_messageInfo_GetReleaseContentResponse.Size(m)
}
func (m *GetReleaseContentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReleaseContentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetReleaseContentResponse proto.InternalMessageInfo

func (m *GetReleaseContentResponse) GetRelease() *release.Release {
	if m != nil {
		return m.Release
	}
	return nil
}

// UpdateReleaseRequest updates a release.
type UpdateReleaseRequest struct {
	// The name of the release
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Chart is the protobuf representation of a chart.
	Chart *chart.Chart `protobuf:"bytes,2,opt,name=chart,proto3" json:"chart,omitempty"`
	// Values is a string containing (unparsed) YAML values.
	Values *chart.Config `protobuf:"bytes,3,opt,name=values,proto3" json:"values,omitempty"`
	// dry_run, if true, will run through the release logic, but neither create
	DryRun bool `protobuf:"varint,4,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	// DisableHooks causes the server to skip running any hooks for the upgrade.
	DisableHooks bool `protobuf:"varint,5,opt,name=disable_hooks,json=disableHooks,proto3" json:"disable_hooks,omitempty"`
	// Performs pods restart for resources if applicable
	Recreate bool `protobuf:"varint,6,opt,name=recreate,proto3" json:"recreate,omitempty"`
	// timeout specifies the max amount of time any kubernetes client command can run.
	Timeout int64 `protobuf:"varint,7,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// ResetValues will cause Tiller to ignore stored values, resetting to default values.
	ResetValues bool `protobuf:"varint,8,opt,name=reset_values,json=resetValues,proto3" json:"reset_values,omitempty"`
	// wait, if true, will wait until all Pods, PVCs, and Services are in a ready state
	// before marking the release as successful. It will wait for as long as timeout
	Wait bool `protobuf:"varint,9,opt,name=wait,proto3" json:"wait,omitempty"`
	// ReuseValues will cause Tiller to reuse the values from the last release.
	// This is ignored if reset_values is set.
	ReuseValues bool `protobuf:"varint,10,opt,name=reuse_values,json=reuseValues,proto3" json:"reuse_values,omitempty"`
	// Force resource update through delete/recreate if needed.
	Force bool `protobuf:"varint,11,opt,name=force,proto3" json:"force,omitempty"`
	// URL to download chart archive
	ChartUrl string `protobuf:"bytes,12,opt,name=chart_url,json=chartUrl,proto3" json:"chart_url,omitempty"`
	// `ca_bundle` is a PEM encoded CA bundle used to sign server certificate of chart repository.
	// +optional
	CaBundle []byte `protobuf:"bytes,13,opt,name=ca_bundle,json=caBundle,proto3" json:"ca_bundle,omitempty"`
	// Username is the username for basic authentication to the chart repository.
	// +optional
	Username string `protobuf:"bytes,14,opt,name=username,proto3" json:"username,omitempty"`
	// Password is the password for basic authentication to the chart repository.
	// +optional
	Password string `protobuf:"bytes,15,opt,name=password,proto3" json:"password,omitempty"`
	// Token is the bearer token for authentication to the chart repository.
	// +optional
	Token string `protobuf:"bytes,16,opt,name=token,proto3" json:"token,omitempty"`
	// ClientCertificate contains PEM-encoded data passed as a client cert to chart repository.
	// +optional
	ClientCertificate []byte `protobuf:"bytes,17,opt,name=client_certificate,json=clientCertificate,proto3" json:"client_certificate,omitempty"`
	// ClientKey contains PEM-encoded data passed as a client key to chart repository.
	// +optional
	ClientKey []byte `protobuf:"bytes,18,opt,name=client_key,json=clientKey,proto3" json:"client_key,omitempty"`
	// Skip certificate verification for chart repository.
	// +optional
	InsecureSkipVerify   bool     `protobuf:"varint,19,opt,name=insecure_skip_verify,json=insecureSkipVerify,proto3" json:"insecure_skip_verify,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateReleaseRequest) Reset()         { *m = UpdateReleaseRequest{} }
func (m *UpdateReleaseRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateReleaseRequest) ProtoMessage()    {}
func (*UpdateReleaseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_tiller_c329dcad7a585ca8, []int{8}
}
func (m *UpdateReleaseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateReleaseRequest.Unmarshal(m, b)
}
func (m *UpdateReleaseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateReleaseRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateReleaseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateReleaseRequest.Merge(dst, src)
}
func (m *UpdateReleaseRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateReleaseRequest.Size(m)
}
func (m *UpdateReleaseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateReleaseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateReleaseRequest proto.InternalMessageInfo

func (m *UpdateReleaseRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateReleaseRequest) GetChart() *chart.Chart {
	if m != nil {
		return m.Chart
	}
	return nil
}

func (m *UpdateReleaseRequest) GetValues() *chart.Config {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *UpdateReleaseRequest) GetDryRun() bool {
	if m != nil {
		return m.DryRun
	}
	return false
}

func (m *UpdateReleaseRequest) GetDisableHooks() bool {
	if m != nil {
		return m.DisableHooks
	}
	return false
}

func (m *UpdateReleaseRequest) GetRecreate() bool {
	if m != nil {
		return m.Recreate
	}
	return false
}

func (m *UpdateReleaseRequest) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *UpdateReleaseRequest) GetResetValues() bool {
	if m != nil {
		return m.ResetValues
	}
	return false
}

func (m *UpdateReleaseRequest) GetWait() bool {
	if m != nil {
		return m.Wait
	}
	return false
}

func (m *UpdateReleaseRequest) GetReuseValues() bool {
	if m != nil {
		return m.ReuseValues
	}
	return false
}

func (m *UpdateReleaseRequest) GetForce() bool {
	if m != nil {
		return m.Force
	}
	return false
}

func (m *UpdateReleaseRequest) GetChartUrl() string {
	if m != nil {
		return m.ChartUrl
	}
	return ""
}

func (m *UpdateReleaseRequest) GetCaBundle() []byte {
	if m != nil {
		return m.CaBundle
	}
	return nil
}

func (m *UpdateReleaseRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UpdateReleaseRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UpdateReleaseRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *UpdateReleaseRequest) GetClientCertificate() []byte {
	if m != nil {
		return m.ClientCertificate
	}
	return nil
}

func (m *UpdateReleaseRequest) GetClientKey() []byte {
	if m != nil {
		return m.ClientKey
	}
	return nil
}

func (m *UpdateReleaseRequest) GetInsecureSkipVerify() bool {
	if m != nil {
		return m.InsecureSkipVerify
	}
	return false
}

// UpdateReleaseResponse is the response to an update request.
type UpdateReleaseResponse struct {
	Release              *release.Release `protobuf:"bytes,1,opt,name=release,proto3" json:"release,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UpdateReleaseResponse) Reset()         { *m = UpdateReleaseResponse{} }
func (m *UpdateReleaseResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateReleaseResponse) ProtoMessage()    {}
func (*UpdateReleaseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_tiller_c329dcad7a585ca8, []int{9}
}
func (m *UpdateReleaseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateReleaseResponse.Unmarshal(m, b)
}
func (m *UpdateReleaseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateReleaseResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateReleaseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateReleaseResponse.Merge(dst, src)
}
func (m *UpdateReleaseResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateReleaseResponse.Size(m)
}
func (m *UpdateReleaseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateReleaseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateReleaseResponse proto.InternalMessageInfo

func (m *UpdateReleaseResponse) GetRelease() *release.Release {
	if m != nil {
		return m.Release
	}
	return nil
}

type RollbackReleaseRequest struct {
	// The name of the release
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// dry_run, if true, will run through the release logic but no create
	DryRun bool `protobuf:"varint,2,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	// DisableHooks causes the server to skip running any hooks for the rollback
	DisableHooks bool `protobuf:"varint,3,opt,name=disable_hooks,json=disableHooks,proto3" json:"disable_hooks,omitempty"`
	// Version is the version of the release to deploy.
	Version int32 `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	// Performs pods restart for resources if applicable
	Recreate bool `protobuf:"varint,5,opt,name=recreate,proto3" json:"recreate,omitempty"`
	// timeout specifies the max amount of time any kubernetes client command can run.
	Timeout int64 `protobuf:"varint,6,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// wait, if true, will wait until all Pods, PVCs, and Services are in a ready state
	// before marking the release as successful. It will wait for as long as timeout
	Wait bool `protobuf:"varint,7,opt,name=wait,proto3" json:"wait,omitempty"`
	// Force resource update through delete/recreate if needed.
	Force                bool     `protobuf:"varint,8,opt,name=force,proto3" json:"force,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RollbackReleaseRequest) Reset()         { *m = RollbackReleaseRequest{} }
func (m *RollbackReleaseRequest) String() string { return proto.CompactTextString(m) }
func (*RollbackReleaseRequest) ProtoMessage()    {}
func (*RollbackReleaseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_tiller_c329dcad7a585ca8, []int{10}
}
func (m *RollbackReleaseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RollbackReleaseRequest.Unmarshal(m, b)
}
func (m *RollbackReleaseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RollbackReleaseRequest.Marshal(b, m, deterministic)
}
func (dst *RollbackReleaseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RollbackReleaseRequest.Merge(dst, src)
}
func (m *RollbackReleaseRequest) XXX_Size() int {
	return xxx_messageInfo_RollbackReleaseRequest.Size(m)
}
func (m *RollbackReleaseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RollbackReleaseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RollbackReleaseRequest proto.InternalMessageInfo

func (m *RollbackReleaseRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RollbackReleaseRequest) GetDryRun() bool {
	if m != nil {
		return m.DryRun
	}
	return false
}

func (m *RollbackReleaseRequest) GetDisableHooks() bool {
	if m != nil {
		return m.DisableHooks
	}
	return false
}

func (m *RollbackReleaseRequest) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *RollbackReleaseRequest) GetRecreate() bool {
	if m != nil {
		return m.Recreate
	}
	return false
}

func (m *RollbackReleaseRequest) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *RollbackReleaseRequest) GetWait() bool {
	if m != nil {
		return m.Wait
	}
	return false
}

func (m *RollbackReleaseRequest) GetForce() bool {
	if m != nil {
		return m.Force
	}
	return false
}

// RollbackReleaseResponse is the response to an update request.
type RollbackReleaseResponse struct {
	Release              *release.Release `protobuf:"bytes,1,opt,name=release,proto3" json:"release,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *RollbackReleaseResponse) Reset()         { *m = RollbackReleaseResponse{} }
func (m *RollbackReleaseResponse) String() string { return proto.CompactTextString(m) }
func (*RollbackReleaseResponse) ProtoMessage()    {}
func (*RollbackReleaseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_tiller_c329dcad7a585ca8, []int{11}
}
func (m *RollbackReleaseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RollbackReleaseResponse.Unmarshal(m, b)
}
func (m *RollbackReleaseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RollbackReleaseResponse.Marshal(b, m, deterministic)
}
func (dst *RollbackReleaseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RollbackReleaseResponse.Merge(dst, src)
}
func (m *RollbackReleaseResponse) XXX_Size() int {
	return xxx_messageInfo_RollbackReleaseResponse.Size(m)
}
func (m *RollbackReleaseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RollbackReleaseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RollbackReleaseResponse proto.InternalMessageInfo

func (m *RollbackReleaseResponse) GetRelease() *release.Release {
	if m != nil {
		return m.Release
	}
	return nil
}

// InstallReleaseRequest is the request for an installation of a chart.
type InstallReleaseRequest struct {
	// Chart is the protobuf representation of a chart.
	Chart *chart.Chart `protobuf:"bytes,1,opt,name=chart,proto3" json:"chart,omitempty"`
	// Values is a string containing (unparsed) YAML values.
	Values *chart.Config `protobuf:"bytes,2,opt,name=values,proto3" json:"values,omitempty"`
	// DryRun, if true, will run through the release logic, but neither create
	// a release object nor deploy to Kubernetes. The release object returned
	// in the response will be fake.
	DryRun bool `protobuf:"varint,3,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	// Name is the candidate release name. This must be unique to the
	// namespace, otherwise the server will return an error. If it is not
	// supplied, the server will autogenerate one.
	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	// DisableHooks causes the server to skip running any hooks for the install.
	DisableHooks bool `protobuf:"varint,5,opt,name=disable_hooks,json=disableHooks,proto3" json:"disable_hooks,omitempty"`
	// Namepace is the kubernetes namespace of the release.
	Namespace string `protobuf:"bytes,6,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// ReuseName requests that Tiller re-uses a name, instead of erroring out.
	ReuseName bool `protobuf:"varint,7,opt,name=reuse_name,json=reuseName,proto3" json:"reuse_name,omitempty"`
	// timeout specifies the max amount of time any kubernetes client command can run.
	Timeout int64 `protobuf:"varint,8,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// wait, if true, will wait until all Pods, PVCs, and Services are in a ready state
	// before marking the release as successful. It will wait for as long as timeout
	Wait bool `protobuf:"varint,9,opt,name=wait,proto3" json:"wait,omitempty"`
	// URL to download chart archive
	ChartUrl string `protobuf:"bytes,10,opt,name=chart_url,json=chartUrl,proto3" json:"chart_url,omitempty"`
	// `ca_bundle` is a PEM encoded CA bundle used to sign server certificate of chart repository.
	// +optional
	CaBundle []byte `protobuf:"bytes,11,opt,name=ca_bundle,json=caBundle,proto3" json:"ca_bundle,omitempty"`
	// Username is the username for basic authentication to the chart repository.
	// +optional
	Username string `protobuf:"bytes,12,opt,name=username,proto3" json:"username,omitempty"`
	// Password is the password for basic authentication to the chart repository.
	// +optional
	Password string `protobuf:"bytes,13,opt,name=password,proto3" json:"password,omitempty"`
	// Token is the bearer token for authentication to the chart repository.
	// +optional
	Token string `protobuf:"bytes,14,opt,name=token,proto3" json:"token,omitempty"`
	// ClientCertificate contains PEM-encoded data passed as a client cert to chart repository.
	// +optional
	ClientCertificate []byte `protobuf:"bytes,15,opt,name=client_certificate,json=clientCertificate,proto3" json:"client_certificate,omitempty"`
	// ClientKey contains PEM-encoded data passed as a client key to chart repository.
	// +optional
	ClientKey []byte `protobuf:"bytes,16,opt,name=client_key,json=clientKey,proto3" json:"client_key,omitempty"`
	// Skip certificate verification for chart repository.
	// +optional
	InsecureSkipVerify   bool     `protobuf:"varint,17,opt,name=insecure_skip_verify,json=insecureSkipVerify,proto3" json:"insecure_skip_verify,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstallReleaseRequest) Reset()         { *m = InstallReleaseRequest{} }
func (m *InstallReleaseRequest) String() string { return proto.CompactTextString(m) }
func (*InstallReleaseRequest) ProtoMessage()    {}
func (*InstallReleaseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_tiller_c329dcad7a585ca8, []int{12}
}
func (m *InstallReleaseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstallReleaseRequest.Unmarshal(m, b)
}
func (m *InstallReleaseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstallReleaseRequest.Marshal(b, m, deterministic)
}
func (dst *InstallReleaseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstallReleaseRequest.Merge(dst, src)
}
func (m *InstallReleaseRequest) XXX_Size() int {
	return xxx_messageInfo_InstallReleaseRequest.Size(m)
}
func (m *InstallReleaseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InstallReleaseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InstallReleaseRequest proto.InternalMessageInfo

func (m *InstallReleaseRequest) GetChart() *chart.Chart {
	if m != nil {
		return m.Chart
	}
	return nil
}

func (m *InstallReleaseRequest) GetValues() *chart.Config {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *InstallReleaseRequest) GetDryRun() bool {
	if m != nil {
		return m.DryRun
	}
	return false
}

func (m *InstallReleaseRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *InstallReleaseRequest) GetDisableHooks() bool {
	if m != nil {
		return m.DisableHooks
	}
	return false
}

func (m *InstallReleaseRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *InstallReleaseRequest) GetReuseName() bool {
	if m != nil {
		return m.ReuseName
	}
	return false
}

func (m *InstallReleaseRequest) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *InstallReleaseRequest) GetWait() bool {
	if m != nil {
		return m.Wait
	}
	return false
}

func (m *InstallReleaseRequest) GetChartUrl() string {
	if m != nil {
		return m.ChartUrl
	}
	return ""
}

func (m *InstallReleaseRequest) GetCaBundle() []byte {
	if m != nil {
		return m.CaBundle
	}
	return nil
}

func (m *InstallReleaseRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *InstallReleaseRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *InstallReleaseRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *InstallReleaseRequest) GetClientCertificate() []byte {
	if m != nil {
		return m.ClientCertificate
	}
	return nil
}

func (m *InstallReleaseRequest) GetClientKey() []byte {
	if m != nil {
		return m.ClientKey
	}
	return nil
}

func (m *InstallReleaseRequest) GetInsecureSkipVerify() bool {
	if m != nil {
		return m.InsecureSkipVerify
	}
	return false
}

// InstallReleaseResponse is the response from a release installation.
type InstallReleaseResponse struct {
	Release              *release.Release `protobuf:"bytes,1,opt,name=release,proto3" json:"release,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *InstallReleaseResponse) Reset()         { *m = InstallReleaseResponse{} }
func (m *InstallReleaseResponse) String() string { return proto.CompactTextString(m) }
func (*InstallReleaseResponse) ProtoMessage()    {}
func (*InstallReleaseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_tiller_c329dcad7a585ca8, []int{13}
}
func (m *InstallReleaseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstallReleaseResponse.Unmarshal(m, b)
}
func (m *InstallReleaseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstallReleaseResponse.Marshal(b, m, deterministic)
}
func (dst *InstallReleaseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstallReleaseResponse.Merge(dst, src)
}
func (m *InstallReleaseResponse) XXX_Size() int {
	return xxx_messageInfo_InstallReleaseResponse.Size(m)
}
func (m *InstallReleaseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InstallReleaseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InstallReleaseResponse proto.InternalMessageInfo

func (m *InstallReleaseResponse) GetRelease() *release.Release {
	if m != nil {
		return m.Release
	}
	return nil
}

// UninstallReleaseRequest represents a request to uninstall a named release.
type UninstallReleaseRequest struct {
	// Name is the name of the release to delete.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// DisableHooks causes the server to skip running any hooks for the uninstall.
	DisableHooks bool `protobuf:"varint,2,opt,name=disable_hooks,json=disableHooks,proto3" json:"disable_hooks,omitempty"`
	// Purge removes the release from the store and make its name free for later use.
	Purge bool `protobuf:"varint,3,opt,name=purge,proto3" json:"purge,omitempty"`
	// timeout specifies the max amount of time any kubernetes client command can run.
	Timeout              int64    `protobuf:"varint,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UninstallReleaseRequest) Reset()         { *m = UninstallReleaseRequest{} }
func (m *UninstallReleaseRequest) String() string { return proto.CompactTextString(m) }
func (*UninstallReleaseRequest) ProtoMessage()    {}
func (*UninstallReleaseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_tiller_c329dcad7a585ca8, []int{14}
}
func (m *UninstallReleaseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UninstallReleaseRequest.Unmarshal(m, b)
}
func (m *UninstallReleaseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UninstallReleaseRequest.Marshal(b, m, deterministic)
}
func (dst *UninstallReleaseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UninstallReleaseRequest.Merge(dst, src)
}
func (m *UninstallReleaseRequest) XXX_Size() int {
	return xxx_messageInfo_UninstallReleaseRequest.Size(m)
}
func (m *UninstallReleaseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UninstallReleaseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UninstallReleaseRequest proto.InternalMessageInfo

func (m *UninstallReleaseRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UninstallReleaseRequest) GetDisableHooks() bool {
	if m != nil {
		return m.DisableHooks
	}
	return false
}

func (m *UninstallReleaseRequest) GetPurge() bool {
	if m != nil {
		return m.Purge
	}
	return false
}

func (m *UninstallReleaseRequest) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

// UninstallReleaseResponse represents a successful response to an uninstall request.
type UninstallReleaseResponse struct {
	// Release is the release that was marked deleted.
	Release *release.Release `protobuf:"bytes,1,opt,name=release,proto3" json:"release,omitempty"`
	// Info is an uninstall message
	Info                 string   `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UninstallReleaseResponse) Reset()         { *m = UninstallReleaseResponse{} }
func (m *UninstallReleaseResponse) String() string { return proto.CompactTextString(m) }
func (*UninstallReleaseResponse) ProtoMessage()    {}
func (*UninstallReleaseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_tiller_c329dcad7a585ca8, []int{15}
}
func (m *UninstallReleaseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UninstallReleaseResponse.Unmarshal(m, b)
}
func (m *UninstallReleaseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UninstallReleaseResponse.Marshal(b, m, deterministic)
}
func (dst *UninstallReleaseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UninstallReleaseResponse.Merge(dst, src)
}
func (m *UninstallReleaseResponse) XXX_Size() int {
	return xxx_messageInfo_UninstallReleaseResponse.Size(m)
}
func (m *UninstallReleaseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UninstallReleaseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UninstallReleaseResponse proto.InternalMessageInfo

func (m *UninstallReleaseResponse) GetRelease() *release.Release {
	if m != nil {
		return m.Release
	}
	return nil
}

func (m *UninstallReleaseResponse) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

// GetVersionRequest requests for version information.
type GetVersionRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVersionRequest) Reset()         { *m = GetVersionRequest{} }
func (m *GetVersionRequest) String() string { return proto.CompactTextString(m) }
func (*GetVersionRequest) ProtoMessage()    {}
func (*GetVersionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_tiller_c329dcad7a585ca8, []int{16}
}
func (m *GetVersionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVersionRequest.Unmarshal(m, b)
}
func (m *GetVersionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVersionRequest.Marshal(b, m, deterministic)
}
func (dst *GetVersionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVersionRequest.Merge(dst, src)
}
func (m *GetVersionRequest) XXX_Size() int {
	return xxx_messageInfo_GetVersionRequest.Size(m)
}
func (m *GetVersionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVersionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetVersionRequest proto.InternalMessageInfo

type GetVersionResponse struct {
	Version              *version.Version `protobuf:"bytes,1,opt,name=Version,proto3" json:"Version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetVersionResponse) Reset()         { *m = GetVersionResponse{} }
func (m *GetVersionResponse) String() string { return proto.CompactTextString(m) }
func (*GetVersionResponse) ProtoMessage()    {}
func (*GetVersionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_tiller_c329dcad7a585ca8, []int{17}
}
func (m *GetVersionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVersionResponse.Unmarshal(m, b)
}
func (m *GetVersionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVersionResponse.Marshal(b, m, deterministic)
}
func (dst *GetVersionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVersionResponse.Merge(dst, src)
}
func (m *GetVersionResponse) XXX_Size() int {
	return xxx_messageInfo_GetVersionResponse.Size(m)
}
func (m *GetVersionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVersionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetVersionResponse proto.InternalMessageInfo

func (m *GetVersionResponse) GetVersion() *version.Version {
	if m != nil {
		return m.Version
	}
	return nil
}

// GetHistoryRequest requests a release's history.
type GetHistoryRequest struct {
	// The name of the release.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The maximum number of releases to include.
	Max                  int32    `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHistoryRequest) Reset()         { *m = GetHistoryRequest{} }
func (m *GetHistoryRequest) String() string { return proto.CompactTextString(m) }
func (*GetHistoryRequest) ProtoMessage()    {}
func (*GetHistoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_tiller_c329dcad7a585ca8, []int{18}
}
func (m *GetHistoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHistoryRequest.Unmarshal(m, b)
}
func (m *GetHistoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHistoryRequest.Marshal(b, m, deterministic)
}
func (dst *GetHistoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHistoryRequest.Merge(dst, src)
}
func (m *GetHistoryRequest) XXX_Size() int {
	return xxx_messageInfo_GetHistoryRequest.Size(m)
}
func (m *GetHistoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHistoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetHistoryRequest proto.InternalMessageInfo

func (m *GetHistoryRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetHistoryRequest) GetMax() int32 {
	if m != nil {
		return m.Max
	}
	return 0
}

// GetHistoryResponse is received in response to a GetHistory rpc.
type GetHistoryResponse struct {
	Releases             []*release.Release `protobuf:"bytes,1,rep,name=releases,proto3" json:"releases,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetHistoryResponse) Reset()         { *m = GetHistoryResponse{} }
func (m *GetHistoryResponse) String() string { return proto.CompactTextString(m) }
func (*GetHistoryResponse) ProtoMessage()    {}
func (*GetHistoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_tiller_c329dcad7a585ca8, []int{19}
}
func (m *GetHistoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHistoryResponse.Unmarshal(m, b)
}
func (m *GetHistoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHistoryResponse.Marshal(b, m, deterministic)
}
func (dst *GetHistoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHistoryResponse.Merge(dst, src)
}
func (m *GetHistoryResponse) XXX_Size() int {
	return xxx_messageInfo_GetHistoryResponse.Size(m)
}
func (m *GetHistoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHistoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetHistoryResponse proto.InternalMessageInfo

func (m *GetHistoryResponse) GetReleases() []*release.Release {
	if m != nil {
		return m.Releases
	}
	return nil
}

func init() {
	proto.RegisterType((*SummarizeReleasesRequest)(nil), "appscode.swift.v2.SummarizeReleasesRequest")
	proto.RegisterType((*ListSort)(nil), "appscode.swift.v2.ListSort")
	proto.RegisterType((*SummarizeReleasesResponse)(nil), "appscode.swift.v2.SummarizeReleasesResponse")
	proto.RegisterType((*ReleaseSummary)(nil), "appscode.swift.v2.ReleaseSummary")
	proto.RegisterType((*GetReleaseStatusRequest)(nil), "appscode.swift.v2.GetReleaseStatusRequest")
	proto.RegisterType((*GetReleaseStatusResponse)(nil), "appscode.swift.v2.GetReleaseStatusResponse")
	proto.RegisterType((*GetReleaseContentRequest)(nil), "appscode.swift.v2.GetReleaseContentRequest")
	proto.RegisterType((*GetReleaseContentResponse)(nil), "appscode.swift.v2.GetReleaseContentResponse")
	proto.RegisterType((*UpdateReleaseRequest)(nil), "appscode.swift.v2.UpdateReleaseRequest")
	proto.RegisterType((*UpdateReleaseResponse)(nil), "appscode.swift.v2.UpdateReleaseResponse")
	proto.RegisterType((*RollbackReleaseRequest)(nil), "appscode.swift.v2.RollbackReleaseRequest")
	proto.RegisterType((*RollbackReleaseResponse)(nil), "appscode.swift.v2.RollbackReleaseResponse")
	proto.RegisterType((*InstallReleaseRequest)(nil), "appscode.swift.v2.InstallReleaseRequest")
	proto.RegisterType((*InstallReleaseResponse)(nil), "appscode.swift.v2.InstallReleaseResponse")
	proto.RegisterType((*UninstallReleaseRequest)(nil), "appscode.swift.v2.UninstallReleaseRequest")
	proto.RegisterType((*UninstallReleaseResponse)(nil), "appscode.swift.v2.UninstallReleaseResponse")
	proto.RegisterType((*GetVersionRequest)(nil), "appscode.swift.v2.GetVersionRequest")
	proto.RegisterType((*GetVersionResponse)(nil), "appscode.swift.v2.GetVersionResponse")
	proto.RegisterType((*GetHistoryRequest)(nil), "appscode.swift.v2.GetHistoryRequest")
	proto.RegisterType((*GetHistoryResponse)(nil), "appscode.swift.v2.GetHistoryResponse")
	proto.RegisterEnum("appscode.swift.v2.ListSort_SortBy", ListSort_SortBy_name, ListSort_SortBy_value)
	proto.RegisterEnum("appscode.swift.v2.ListSort_SortOrder", ListSort_SortOrder_name, ListSort_SortOrder_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ReleaseServiceClient is the client API for ReleaseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ReleaseServiceClient interface {
	// SummarizeReleases retrieves summary of release history.
	// TODO: Allow filtering the set of releases by
	// release status. By default, SummarizeReleases returns the releases who
	// current status is "Active".
	SummarizeReleases(ctx context.Context, in *SummarizeReleasesRequest, opts ...grpc.CallOption) (*SummarizeReleasesResponse, error)
	// GetReleasesStatus retrieves status information for the specified release.
	GetReleaseStatus(ctx context.Context, in *GetReleaseStatusRequest, opts ...grpc.CallOption) (*GetReleaseStatusResponse, error)
	// GetReleaseContent retrieves the release content (chart + value) for the specified release.
	GetReleaseContent(ctx context.Context, in *GetReleaseContentRequest, opts ...grpc.CallOption) (*GetReleaseContentResponse, error)
	// UpdateRelease updates release content.
	UpdateRelease(ctx context.Context, in *UpdateReleaseRequest, opts ...grpc.CallOption) (*UpdateReleaseResponse, error)
	// InstallRelease requests installation of a chart as a new release.
	InstallRelease(ctx context.Context, in *InstallReleaseRequest, opts ...grpc.CallOption) (*InstallReleaseResponse, error)
	// UninstallRelease requests deletion of a named release.
	UninstallRelease(ctx context.Context, in *UninstallReleaseRequest, opts ...grpc.CallOption) (*UninstallReleaseResponse, error)
	// GetVersion returns the current version of the server.
	GetVersion(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*GetVersionResponse, error)
	// RollbackRelease rolls back a release to a previous version.
	RollbackRelease(ctx context.Context, in *RollbackReleaseRequest, opts ...grpc.CallOption) (*RollbackReleaseResponse, error)
	// ReleaseHistory retrieves a releasse's history.
	GetHistory(ctx context.Context, in *GetHistoryRequest, opts ...grpc.CallOption) (*GetHistoryResponse, error)
}

type releaseServiceClient struct {
	cc *grpc.ClientConn
}

func NewReleaseServiceClient(cc *grpc.ClientConn) ReleaseServiceClient {
	return &releaseServiceClient{cc}
}

func (c *releaseServiceClient) SummarizeReleases(ctx context.Context, in *SummarizeReleasesRequest, opts ...grpc.CallOption) (*SummarizeReleasesResponse, error) {
	out := new(SummarizeReleasesResponse)
	err := c.cc.Invoke(ctx, "/appscode.swift.v2.ReleaseService/SummarizeReleases", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *releaseServiceClient) GetReleaseStatus(ctx context.Context, in *GetReleaseStatusRequest, opts ...grpc.CallOption) (*GetReleaseStatusResponse, error) {
	out := new(GetReleaseStatusResponse)
	err := c.cc.Invoke(ctx, "/appscode.swift.v2.ReleaseService/GetReleaseStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *releaseServiceClient) GetReleaseContent(ctx context.Context, in *GetReleaseContentRequest, opts ...grpc.CallOption) (*GetReleaseContentResponse, error) {
	out := new(GetReleaseContentResponse)
	err := c.cc.Invoke(ctx, "/appscode.swift.v2.ReleaseService/GetReleaseContent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *releaseServiceClient) UpdateRelease(ctx context.Context, in *UpdateReleaseRequest, opts ...grpc.CallOption) (*UpdateReleaseResponse, error) {
	out := new(UpdateReleaseResponse)
	err := c.cc.Invoke(ctx, "/appscode.swift.v2.ReleaseService/UpdateRelease", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *releaseServiceClient) InstallRelease(ctx context.Context, in *InstallReleaseRequest, opts ...grpc.CallOption) (*InstallReleaseResponse, error) {
	out := new(InstallReleaseResponse)
	err := c.cc.Invoke(ctx, "/appscode.swift.v2.ReleaseService/InstallRelease", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *releaseServiceClient) UninstallRelease(ctx context.Context, in *UninstallReleaseRequest, opts ...grpc.CallOption) (*UninstallReleaseResponse, error) {
	out := new(UninstallReleaseResponse)
	err := c.cc.Invoke(ctx, "/appscode.swift.v2.ReleaseService/UninstallRelease", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *releaseServiceClient) GetVersion(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*GetVersionResponse, error) {
	out := new(GetVersionResponse)
	err := c.cc.Invoke(ctx, "/appscode.swift.v2.ReleaseService/GetVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *releaseServiceClient) RollbackRelease(ctx context.Context, in *RollbackReleaseRequest, opts ...grpc.CallOption) (*RollbackReleaseResponse, error) {
	out := new(RollbackReleaseResponse)
	err := c.cc.Invoke(ctx, "/appscode.swift.v2.ReleaseService/RollbackRelease", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *releaseServiceClient) GetHistory(ctx context.Context, in *GetHistoryRequest, opts ...grpc.CallOption) (*GetHistoryResponse, error) {
	out := new(GetHistoryResponse)
	err := c.cc.Invoke(ctx, "/appscode.swift.v2.ReleaseService/GetHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReleaseServiceServer is the server API for ReleaseService service.
type ReleaseServiceServer interface {
	// SummarizeReleases retrieves summary of release history.
	// TODO: Allow filtering the set of releases by
	// release status. By default, SummarizeReleases returns the releases who
	// current status is "Active".
	SummarizeReleases(context.Context, *SummarizeReleasesRequest) (*SummarizeReleasesResponse, error)
	// GetReleasesStatus retrieves status information for the specified release.
	GetReleaseStatus(context.Context, *GetReleaseStatusRequest) (*GetReleaseStatusResponse, error)
	// GetReleaseContent retrieves the release content (chart + value) for the specified release.
	GetReleaseContent(context.Context, *GetReleaseContentRequest) (*GetReleaseContentResponse, error)
	// UpdateRelease updates release content.
	UpdateRelease(context.Context, *UpdateReleaseRequest) (*UpdateReleaseResponse, error)
	// InstallRelease requests installation of a chart as a new release.
	InstallRelease(context.Context, *InstallReleaseRequest) (*InstallReleaseResponse, error)
	// UninstallRelease requests deletion of a named release.
	UninstallRelease(context.Context, *UninstallReleaseRequest) (*UninstallReleaseResponse, error)
	// GetVersion returns the current version of the server.
	GetVersion(context.Context, *GetVersionRequest) (*GetVersionResponse, error)
	// RollbackRelease rolls back a release to a previous version.
	RollbackRelease(context.Context, *RollbackReleaseRequest) (*RollbackReleaseResponse, error)
	// ReleaseHistory retrieves a releasse's history.
	GetHistory(context.Context, *GetHistoryRequest) (*GetHistoryResponse, error)
}

func RegisterReleaseServiceServer(s *grpc.Server, srv ReleaseServiceServer) {
	s.RegisterService(&_ReleaseService_serviceDesc, srv)
}

func _ReleaseService_SummarizeReleases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SummarizeReleasesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReleaseServiceServer).SummarizeReleases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appscode.swift.v2.ReleaseService/SummarizeReleases",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReleaseServiceServer).SummarizeReleases(ctx, req.(*SummarizeReleasesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReleaseService_GetReleaseStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReleaseStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReleaseServiceServer).GetReleaseStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appscode.swift.v2.ReleaseService/GetReleaseStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReleaseServiceServer).GetReleaseStatus(ctx, req.(*GetReleaseStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReleaseService_GetReleaseContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReleaseContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReleaseServiceServer).GetReleaseContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appscode.swift.v2.ReleaseService/GetReleaseContent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReleaseServiceServer).GetReleaseContent(ctx, req.(*GetReleaseContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReleaseService_UpdateRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReleaseServiceServer).UpdateRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appscode.swift.v2.ReleaseService/UpdateRelease",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReleaseServiceServer).UpdateRelease(ctx, req.(*UpdateReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReleaseService_InstallRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstallReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReleaseServiceServer).InstallRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appscode.swift.v2.ReleaseService/InstallRelease",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReleaseServiceServer).InstallRelease(ctx, req.(*InstallReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReleaseService_UninstallRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UninstallReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReleaseServiceServer).UninstallRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appscode.swift.v2.ReleaseService/UninstallRelease",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReleaseServiceServer).UninstallRelease(ctx, req.(*UninstallReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReleaseService_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReleaseServiceServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appscode.swift.v2.ReleaseService/GetVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReleaseServiceServer).GetVersion(ctx, req.(*GetVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReleaseService_RollbackRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReleaseServiceServer).RollbackRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appscode.swift.v2.ReleaseService/RollbackRelease",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReleaseServiceServer).RollbackRelease(ctx, req.(*RollbackReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReleaseService_GetHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReleaseServiceServer).GetHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appscode.swift.v2.ReleaseService/GetHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReleaseServiceServer).GetHistory(ctx, req.(*GetHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ReleaseService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "appscode.swift.v2.ReleaseService",
	HandlerType: (*ReleaseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SummarizeReleases",
			Handler:    _ReleaseService_SummarizeReleases_Handler,
		},
		{
			MethodName: "GetReleaseStatus",
			Handler:    _ReleaseService_GetReleaseStatus_Handler,
		},
		{
			MethodName: "GetReleaseContent",
			Handler:    _ReleaseService_GetReleaseContent_Handler,
		},
		{
			MethodName: "UpdateRelease",
			Handler:    _ReleaseService_UpdateRelease_Handler,
		},
		{
			MethodName: "InstallRelease",
			Handler:    _ReleaseService_InstallRelease_Handler,
		},
		{
			MethodName: "UninstallRelease",
			Handler:    _ReleaseService_UninstallRelease_Handler,
		},
		{
			MethodName: "GetVersion",
			Handler:    _ReleaseService_GetVersion_Handler,
		},
		{
			MethodName: "RollbackRelease",
			Handler:    _ReleaseService_RollbackRelease_Handler,
		},
		{
			MethodName: "GetHistory",
			Handler:    _ReleaseService_GetHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tiller.proto",
}

func init() { proto.RegisterFile("tiller.proto", fileDescriptor_tiller_c329dcad7a585ca8) }

var fileDescriptor_tiller_c329dcad7a585ca8 = []byte{
	// 1590 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x58, 0x4b, 0x73, 0x1b, 0xc5,
	0x13, 0xff, 0xaf, 0x24, 0xeb, 0xd1, 0xb2, 0x1d, 0x69, 0xe2, 0xc7, 0x5a, 0xff, 0xfc, 0xf3, 0x77,
	0x96, 0x3c, 0x14, 0x87, 0xc8, 0x89, 0x78, 0x54, 0x41, 0x8a, 0x83, 0xed, 0xb8, 0x9c, 0x87, 0xe3,
	0xa4, 0xd6, 0x38, 0x54, 0x71, 0x40, 0x35, 0x96, 0x46, 0xce, 0xe2, 0xd5, 0x8e, 0x98, 0x19, 0x39,
	0x11, 0x29, 0xaa, 0xa8, 0x9c, 0xb8, 0x43, 0x41, 0x55, 0x4e, 0x70, 0xe0, 0x03, 0x70, 0x80, 0x2f,
	0xc2, 0x57, 0xc8, 0x8d, 0xe2, 0xc6, 0x07, 0xa0, 0x76, 0x1e, 0xf2, 0xae, 0xbc, 0x92, 0x85, 0xb9,
	0x48, 0xdb, 0xd3, 0x3d, 0xd3, 0xbf, 0xee, 0xfe, 0xf5, 0xa8, 0x57, 0x30, 0x2d, 0x3c, 0xdf, 0x27,
	0xac, 0xd6, 0x65, 0x54, 0x50, 0x54, 0xc6, 0xdd, 0x2e, 0x6f, 0xd2, 0x16, 0xa9, 0xf1, 0xe7, 0x5e,
	0x5b, 0xd4, 0x8e, 0xea, 0x95, 0x85, 0x67, 0xb8, 0xeb, 0xad, 0x36, 0x9f, 0x61, 0x26, 0xd4, 0xa7,
	0x32, 0xad, 0x2c, 0x46, 0xd7, 0x69, 0xd0, 0xf6, 0x0e, 0xb4, 0x62, 0x29, 0xa2, 0xe8, 0x10, 0x81,
	0x5b, 0x58, 0x60, 0xad, 0xaa, 0x48, 0x15, 0x23, 0x3e, 0xc1, 0x9c, 0x98, 0xef, 0xd8, 0x79, 0x46,
	0xe7, 0x05, 0x6d, 0x1a, 0x3b, 0xcf, 0x28, 0xb8, 0xc0, 0xa2, 0xc7, 0x63, 0xe7, 0x1d, 0x11, 0xc6,
	0x3d, 0x1a, 0x98, 0x6f, 0xad, 0xbb, 0x70, 0x40, 0xe9, 0x81, 0x4f, 0x56, 0x43, 0x0b, 0x1c, 0x04,
	0x54, 0x60, 0xe1, 0xd1, 0xc0, 0xec, 0xbc, 0x68, 0x02, 0x4d, 0xd6, 0x3b, 0xbf, 0xa5, 0xc0, 0xde,
	0xed, 0x75, 0x3a, 0x98, 0x79, 0x5f, 0x12, 0x57, 0xf9, 0xe6, 0x2e, 0xf9, 0xa2, 0x47, 0xb8, 0x40,
	0x73, 0x30, 0xe5, 0x7b, 0x1d, 0x4f, 0xd8, 0xd6, 0xb2, 0x55, 0x4d, 0xbb, 0x4a, 0x40, 0x0b, 0x90,
	0xa5, 0xed, 0x36, 0x27, 0xc2, 0x4e, 0x2d, 0x5b, 0xd5, 0x82, 0xab, 0x25, 0x74, 0x07, 0x72, 0x9c,
	0x32, 0xd1, 0xd8, 0xef, 0xdb, 0xe9, 0x65, 0xab, 0x3a, 0x5b, 0x77, 0x6a, 0x27, 0xb2, 0x5c, 0xdb,
	0xf6, 0xb8, 0xd8, 0xa5, 0x4c, 0xd4, 0xc2, 0x8f, 0xf5, 0xbe, 0x9b, 0xe5, 0xf2, 0x3b, 0x3c, 0xb4,
	0xed, 0xf9, 0x82, 0x30, 0x3b, 0xa3, 0x0e, 0x55, 0x12, 0xba, 0x0b, 0x20, 0x0f, 0xa5, 0xac, 0x45,
	0x98, 0x3d, 0x25, 0xcf, 0xbd, 0x72, 0xda, 0xb9, 0x8f, 0x43, 0x63, 0xb7, 0xc0, 0xcd, 0x23, 0xba,
	0x04, 0xd3, 0x2a, 0x9f, 0x8d, 0x70, 0x17, 0xb7, 0xb3, 0xcb, 0xe9, 0x6a, 0xc1, 0x2d, 0xaa, 0xb5,
	0x8d, 0x70, 0x09, 0x5d, 0x80, 0x42, 0x80, 0x3b, 0x84, 0x77, 0x71, 0x93, 0xd8, 0x39, 0x89, 0xe1,
	0x78, 0x01, 0x95, 0x20, 0x8d, 0x7d, 0xdf, 0xce, 0x2f, 0x5b, 0xd5, 0xbc, 0x1b, 0x3e, 0x3a, 0x9f,
	0x41, 0xde, 0xf8, 0x74, 0xea, 0x90, 0x55, 0xe1, 0xa0, 0x22, 0xe4, 0xf6, 0x76, 0x1e, 0xee, 0x3c,
	0xfe, 0x64, 0xa7, 0xf4, 0x1f, 0x94, 0x87, 0xcc, 0xce, 0xda, 0xa3, 0xcd, 0x92, 0x85, 0xca, 0x30,
	0xb3, 0xbd, 0xb6, 0xfb, 0x71, 0xc3, 0xdd, 0xdc, 0xde, 0x5c, 0xdb, 0xdd, 0xbc, 0x5b, 0x4a, 0x39,
	0x17, 0xa1, 0x30, 0x80, 0x8a, 0x72, 0x90, 0x5e, 0xdb, 0xdd, 0x50, 0x5b, 0xee, 0x6e, 0xee, 0x6e,
	0x94, 0x2c, 0xe7, 0xb5, 0x05, 0x4b, 0x09, 0x85, 0xe1, 0x5d, 0x1a, 0x70, 0x12, 0x56, 0xa6, 0x49,
	0x7b, 0xc1, 0xa0, 0x32, 0x52, 0x40, 0x08, 0x32, 0x01, 0x79, 0x61, 0xea, 0x22, 0x9f, 0x43, 0x4b,
	0x41, 0x05, 0xf6, 0x65, 0x4d, 0xd2, 0xae, 0x12, 0xd0, 0x47, 0x90, 0xd7, 0x44, 0xe3, 0x76, 0x66,
	0x39, 0x5d, 0x2d, 0xd6, 0x2f, 0x25, 0x24, 0x55, 0xbb, 0x55, 0x30, 0xfa, 0xee, 0x60, 0x8b, 0xf3,
	0xa7, 0x05, 0xb3, 0x71, 0xa5, 0xf4, 0x8d, 0x3b, 0x44, 0x02, 0x0a, 0x7d, 0xe3, 0x0e, 0x41, 0x57,
	0x21, 0x13, 0xf2, 0x5b, 0xe2, 0x29, 0xd6, 0x51, 0x2d, 0x64, 0x71, 0xcd, 0x74, 0xc3, 0xfd, 0xa0,
	0x4d, 0x5d, 0xa9, 0x47, 0x77, 0x60, 0x56, 0xb6, 0x51, 0xc3, 0xb4, 0x91, 0x04, 0x5b, 0xac, 0xcf,
	0xa9, 0x1d, 0xaa, 0x1b, 0x1f, 0x69, 0x9d, 0x3b, 0x23, 0x65, 0x23, 0xa2, 0x15, 0xc8, 0xaa, 0xb6,
	0x94, 0xcc, 0x19, 0xb8, 0x51, 0x9b, 0x36, 0xa4, 0xc6, 0xd5, 0x16, 0xc8, 0x86, 0x9c, 0x6e, 0x1e,
	0x49, 0xa5, 0x29, 0xd7, 0x88, 0xf1, 0xf2, 0x67, 0x87, 0xca, 0xef, 0x6c, 0xc1, 0xe2, 0x16, 0x11,
	0x26, 0x62, 0xc9, 0x1a, 0xd3, 0x23, 0x49, 0x71, 0x47, 0xdc, 0xa4, 0x62, 0x6e, 0x1c, 0x01, 0xf6,
	0xc9, 0x83, 0x74, 0x4d, 0xff, 0x4d, 0x06, 0x63, 0xf0, 0xd3, 0xc3, 0xf0, 0x5f, 0x46, 0xbd, 0x6e,
	0xd0, 0x40, 0x90, 0x40, 0x9c, 0x09, 0x3f, 0xba, 0x0d, 0xf3, 0x6d, 0xca, 0x3a, 0x58, 0x34, 0x8e,
	0xb0, 0xdf, 0x23, 0xbc, 0x81, 0x79, 0xe3, 0x73, 0x4e, 0x03, 0xe9, 0x33, 0xef, 0x22, 0xa5, 0x7c,
	0x2a, 0x75, 0x6b, 0xfc, 0x01, 0xa7, 0x81, 0xb3, 0x0d, 0x4b, 0x09, 0xce, 0x75, 0xcc, 0xab, 0x90,
	0xd3, 0xd1, 0x48, 0x00, 0xc5, 0xfa, 0x7c, 0x3c, 0x44, 0xbd, 0xcd, 0x35, 0x56, 0xce, 0x1f, 0x19,
	0x98, 0xdb, 0xeb, 0xb6, 0xb0, 0x30, 0x3d, 0x31, 0x2e, 0x8e, 0x6b, 0x30, 0x25, 0x69, 0xa0, 0xd3,
	0x57, 0x8e, 0x31, 0x23, 0xfc, 0x74, 0x95, 0x3e, 0xe4, 0x90, 0x8a, 0x47, 0x13, 0x2f, 0x91, 0x43,
	0xca, 0x02, 0x2d, 0x42, 0xae, 0xc5, 0xfa, 0x0d, 0xd6, 0x0b, 0x24, 0xe1, 0xf2, 0x6e, 0xb6, 0xc5,
	0xfa, 0x6e, 0x2f, 0x40, 0x6f, 0xc1, 0x4c, 0xcb, 0xe3, 0x78, 0xdf, 0x27, 0x8d, 0x67, 0x94, 0x1e,
	0x72, 0x49, 0xb1, 0xbc, 0x3b, 0xad, 0x17, 0xef, 0x85, 0x6b, 0xa8, 0x12, 0x36, 0x5e, 0x93, 0x11,
	0x2c, 0x14, 0xcd, 0xf2, 0xee, 0x40, 0x0e, 0xd3, 0x2e, 0xbc, 0x0e, 0xa1, 0x3d, 0x21, 0x2f, 0xa0,
	0xb4, 0x6b, 0xc4, 0xf0, 0xfe, 0x62, 0x84, 0x13, 0x93, 0x75, 0x7d, 0x0f, 0x15, 0xe5, 0x9a, 0x4a,
	0x76, 0x18, 0xff, 0x73, 0xec, 0x09, 0xbb, 0x20, 0x55, 0xf2, 0x59, 0x6d, 0xeb, 0x71, 0x62, 0xb6,
	0x81, 0xd9, 0xd6, 0xe3, 0x44, 0x6f, 0x9b, 0x83, 0xa9, 0x36, 0x65, 0x4d, 0x62, 0x17, 0xa5, 0x4e,
	0x09, 0xe8, 0xbf, 0x50, 0x50, 0x0d, 0xd9, 0x63, 0xbe, 0x3d, 0x2d, 0x33, 0x9a, 0x97, 0x0b, 0x7b,
	0xcc, 0x97, 0x4a, 0xdc, 0xd8, 0xef, 0x05, 0x2d, 0x9f, 0xd8, 0x33, 0xcb, 0x56, 0x75, 0xda, 0xcd,
	0x37, 0xf1, 0xba, 0x94, 0xc3, 0xf8, 0x7a, 0x9c, 0x30, 0x59, 0x8a, 0x59, 0xb5, 0xd1, 0xc8, 0xa1,
	0xae, 0x8b, 0x39, 0x7f, 0x4e, 0x59, 0xcb, 0x3e, 0xa7, 0x74, 0x46, 0x56, 0xd7, 0xd4, 0x21, 0x09,
	0xec, 0x92, 0x54, 0x28, 0x01, 0xdd, 0x04, 0xd4, 0xf4, 0x3d, 0x12, 0x88, 0x46, 0x93, 0x30, 0xe1,
	0xb5, 0xbd, 0x66, 0x98, 0xb7, 0xb2, 0xf4, 0x59, 0x56, 0x9a, 0x8d, 0x63, 0x05, 0xfa, 0x1f, 0x80,
	0x36, 0x3f, 0x24, 0x7d, 0x1b, 0x49, 0xb3, 0x82, 0x5a, 0x79, 0x48, 0xfa, 0xe8, 0x16, 0xcc, 0x79,
	0x01, 0x27, 0xcd, 0x1e, 0x23, 0x0d, 0x7e, 0xe8, 0x75, 0x1b, 0x47, 0x84, 0x79, 0xed, 0xbe, 0x7d,
	0x5e, 0x71, 0xd7, 0xe8, 0x76, 0x0f, 0xbd, 0xee, 0x53, 0xa9, 0x71, 0xee, 0xc1, 0xfc, 0x10, 0xd9,
	0xce, 0xca, 0xdb, 0x37, 0x16, 0x2c, 0xb8, 0xd4, 0xf7, 0xf7, 0x71, 0xf3, 0x70, 0x02, 0xe6, 0x46,
	0x48, 0x96, 0x1a, 0x4f, 0xb2, 0x74, 0x02, 0xc9, 0x22, 0xfd, 0x9b, 0x89, 0xf7, 0x6f, 0x94, 0x7e,
	0x53, 0xa3, 0xe9, 0x97, 0x8d, 0xd3, 0xcf, 0x70, 0x2b, 0x17, 0xe1, 0xd6, 0x80, 0x38, 0xf9, 0x08,
	0x71, 0x9c, 0x07, 0xb0, 0x78, 0x22, 0xca, 0xb3, 0xa6, 0xec, 0x97, 0x0c, 0xcc, 0xdf, 0x0f, 0xb8,
	0xc0, 0xbe, 0x3f, 0x94, 0xb1, 0x41, 0x5f, 0x5b, 0x13, 0xf7, 0x75, 0xea, 0x9f, 0xf4, 0x75, 0x3a,
	0x96, 0x72, 0x53, 0x9f, 0x4c, 0xa4, 0x3e, 0x13, 0xf5, 0xfa, 0xd8, 0xdf, 0x94, 0x90, 0xac, 0xaa,
	0x39, 0xe5, 0xe1, 0x2a, 0xb5, 0x05, 0xb9, 0xb2, 0xa3, 0xef, 0x60, 0x53, 0x8d, 0x7c, 0x72, 0x35,
	0xa2, 0x9d, 0x1e, 0x6b, 0x58, 0x18, 0xd7, 0xb0, 0xc5, 0x31, 0x0d, 0x3b, 0x3d, 0xa6, 0x61, 0x67,
	0x46, 0x35, 0xec, 0xec, 0xe9, 0x0d, 0x7b, 0x6e, 0xb2, 0x86, 0x2d, 0x4d, 0xda, 0xb0, 0xe5, 0x91,
	0x0d, 0x7b, 0x1f, 0x16, 0x86, 0x29, 0x73, 0x56, 0xfa, 0xbd, 0xb2, 0x60, 0x71, 0x2f, 0xf0, 0x12,
	0x09, 0x98, 0xd4, 0xb2, 0x27, 0x28, 0x91, 0x4a, 0xa0, 0xc4, 0x1c, 0x4c, 0x75, 0x7b, 0xec, 0x80,
	0x68, 0x8a, 0x29, 0x21, 0x5a, 0xeb, 0x4c, 0xac, 0xd6, 0x4e, 0x03, 0xec, 0x93, 0x18, 0xce, 0x18,
	0x51, 0x88, 0x7a, 0x30, 0x4c, 0x14, 0xd4, 0xe0, 0xe0, 0x9c, 0x87, 0xf2, 0x16, 0x11, 0x4f, 0xd5,
	0xf5, 0xa0, 0xc3, 0x73, 0x36, 0x01, 0x45, 0x17, 0x8f, 0xfd, 0xe9, 0xa5, 0xb8, 0x3f, 0xf3, 0x3a,
	0x62, 0xec, 0x8d, 0x95, 0xf3, 0x81, 0x3c, 0xfb, 0x9e, 0xc7, 0x05, 0x65, 0xfd, 0x71, 0xa9, 0x2b,
	0x41, 0xba, 0x83, 0x5f, 0xe8, 0x59, 0x23, 0x7c, 0x74, 0xb6, 0x24, 0x82, 0xc1, 0x56, 0x8d, 0xe0,
	0x76, 0x64, 0x6a, 0xb5, 0xe4, 0xd4, 0x3a, 0x22, 0xe4, 0x81, 0x59, 0xfd, 0x2f, 0x38, 0x9e, 0x54,
	0x09, 0x3b, 0xf2, 0x9a, 0x04, 0x7d, 0x6f, 0x41, 0xf9, 0xc4, 0x64, 0x8d, 0x6e, 0x24, 0xcc, 0xbf,
	0xa3, 0x5e, 0x8c, 0x2a, 0x6f, 0x4f, 0x66, 0xac, 0x60, 0x3b, 0x57, 0x5f, 0xfd, 0x6a, 0xa7, 0xf2,
	0xd6, 0xab, 0xdf, 0xdf, 0x7c, 0x9b, 0xaa, 0x20, 0x7b, 0x55, 0xbd, 0x89, 0xae, 0x1e, 0xd5, 0xcd,
	0xcb, 0x1e, 0x5f, 0x0d, 0x67, 0x28, 0xf4, 0x93, 0x05, 0xa5, 0xe1, 0xe9, 0x10, 0xad, 0x24, 0xb8,
	0x1a, 0x31, 0x8b, 0x56, 0x6e, 0x4c, 0x64, 0xab, 0x51, 0xbd, 0x1b, 0x41, 0x55, 0x45, 0x57, 0x93,
	0x50, 0xbd, 0x0c, 0xab, 0xf3, 0x95, 0x7e, 0x15, 0x55, 0x18, 0x7f, 0xb6, 0x64, 0x51, 0xe3, 0xe3,
	0x1c, 0x1a, 0xef, 0x38, 0x3e, 0x71, 0x26, 0x26, 0x6f, 0xe4, 0x84, 0xe8, 0xbc, 0x17, 0x81, 0x79,
	0x1d, 0x5d, 0x1b, 0x03, 0xb3, 0xa9, 0x76, 0x2a, 0x9c, 0xdf, 0x59, 0x30, 0x13, 0xfb, 0xe9, 0x46,
	0xd7, 0x12, 0xdc, 0x26, 0x4d, 0x92, 0x95, 0xea, 0xe9, 0x86, 0x1a, 0xdb, 0xad, 0x08, 0xb6, 0xcb,
	0x95, 0xff, 0x8f, 0xc1, 0x16, 0x62, 0xfa, 0xd0, 0x5a, 0x41, 0x3f, 0x58, 0x30, 0x1b, 0xbf, 0xa0,
	0x50, 0x92, 0xbb, 0xc4, 0x9f, 0xbd, 0xca, 0xf5, 0x09, 0x2c, 0x93, 0x90, 0x39, 0x93, 0x20, 0x7b,
	0x6d, 0x41, 0x69, 0xf8, 0xaa, 0x49, 0x24, 0xdf, 0x88, 0x3b, 0x31, 0x91, 0x7c, 0xa3, 0xee, 0x2e,
	0xe7, 0x66, 0x04, 0xdf, 0xa5, 0x95, 0xd3, 0xf0, 0xa1, 0xaf, 0x2d, 0x80, 0xe3, 0x1b, 0x09, 0x5d,
	0x4e, 0x66, 0x50, 0xfc, 0x16, 0xab, 0x5c, 0x39, 0xc5, 0x4a, 0x43, 0xb9, 0x12, 0x81, 0xb2, 0x84,
	0x16, 0x23, 0x50, 0xcc, 0xff, 0x2d, 0x12, 0xc2, 0x8f, 0x16, 0x9c, 0x1b, 0x1a, 0x6d, 0x50, 0x52,
	0x41, 0x92, 0x87, 0xbc, 0xca, 0xca, 0x24, 0xa6, 0x1a, 0xd1, 0xfb, 0x11, 0x44, 0x2b, 0xa8, 0x3a,
	0x26, 0x39, 0x4c, 0x9f, 0xa0, 0x20, 0x7e, 0xa3, 0xb2, 0xa4, 0x6f, 0xcd, 0x51, 0x59, 0x8a, 0xdf,
	0xc7, 0xa3, 0xb2, 0x34, 0x74, 0xf5, 0xc6, 0x0b, 0x86, 0x4e, 0x2b, 0xd8, 0xfa, 0x0d, 0x98, 0x6f,
	0xd2, 0xce, 0xc9, 0xa3, 0xd7, 0xa7, 0x75, 0xb0, 0x4f, 0x18, 0x15, 0xf4, 0x89, 0xf5, 0x69, 0xea,
	0xa8, 0xbe, 0x9f, 0x95, 0x7f, 0x45, 0xbd, 0xf3, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc6, 0x41,
	0x54, 0x11, 0xa3, 0x13, 0x00, 0x00,
}
