// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tiller.proto

/*
Package v2 is a generated protocol buffer package.

It is generated from these files:
	tiller.proto

It has these top-level messages:
	SummarizeReleasesRequest
	ListSort
	SummarizeReleasesResponse
	ReleaseSummary
	GetReleaseStatusRequest
	GetReleaseStatusResponse
	GetReleaseContentRequest
	GetReleaseContentResponse
	UpdateReleaseRequest
	UpdateReleaseResponse
	RollbackReleaseRequest
	RollbackReleaseResponse
	InstallReleaseRequest
	InstallReleaseResponse
	UninstallReleaseRequest
	UninstallReleaseResponse
	GetVersionRequest
	GetVersionResponse
	GetHistoryRequest
	GetHistoryResponse
*/
package v2

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import hapi_chart3 "k8s.io/helm/pkg/proto/hapi/chart"
import hapi_chart "k8s.io/helm/pkg/proto/hapi/chart"
import hapi_chart1 "k8s.io/helm/pkg/proto/hapi/chart"
import hapi_release5 "k8s.io/helm/pkg/proto/hapi/release"
import hapi_release4 "k8s.io/helm/pkg/proto/hapi/release"
import _ "k8s.io/helm/pkg/proto/hapi/release"
import hapi_version "k8s.io/helm/pkg/proto/hapi/version"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import _ "github.com/grpc-ecosystem/grpc-gateway/third_party/appscodeapis/appscode/api"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// SortBy defines sort operations.
type ListSort_SortBy int32

const (
	ListSort_UNKNOWN       ListSort_SortBy = 0
	ListSort_NAME          ListSort_SortBy = 1
	ListSort_LAST_RELEASED ListSort_SortBy = 2
)

var ListSort_SortBy_name = map[int32]string{
	0: "UNKNOWN",
	1: "NAME",
	2: "LAST_RELEASED",
}
var ListSort_SortBy_value = map[string]int32{
	"UNKNOWN":       0,
	"NAME":          1,
	"LAST_RELEASED": 2,
}

func (x ListSort_SortBy) String() string {
	return proto.EnumName(ListSort_SortBy_name, int32(x))
}
func (ListSort_SortBy) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

// SortOrder defines sort orders to augment sorting operations.
type ListSort_SortOrder int32

const (
	ListSort_ASC  ListSort_SortOrder = 0
	ListSort_DESC ListSort_SortOrder = 1
)

var ListSort_SortOrder_name = map[int32]string{
	0: "ASC",
	1: "DESC",
}
var ListSort_SortOrder_value = map[string]int32{
	"ASC":  0,
	"DESC": 1,
}

func (x ListSort_SortOrder) String() string {
	return proto.EnumName(ListSort_SortOrder_name, int32(x))
}
func (ListSort_SortOrder) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 1} }

// SummarizeReleasesRequest requests a list of releases.
//
// Releases can be retrieved in chunks by setting limit and offset.
//
// Releases can be sorted according to a few pre-determined sort stategies.
type SummarizeReleasesRequest struct {
	// Limit is the maximum number of releases to be returned.
	Limit int64 `protobuf:"varint,1,opt,name=limit" json:"limit,omitempty"`
	// Offset is the last release name that was seen. The next listing
	// operation will start with the name after this one.
	// Example: If list one returns albert, bernie, carl, and sets 'next: dennis'.
	// dennis is the offset. Supplying 'dennis' for the next request should
	// cause the next batch to return a set of results starting with 'dennis'.
	Offset string `protobuf:"bytes,2,opt,name=offset" json:"offset,omitempty"`
	// SortBy is the sort field that the ListReleases server should sort data before returning.
	SortBy ListSort_SortBy `protobuf:"varint,3,opt,name=sort_by,json=sortBy,enum=appscode.swift.v2.ListSort_SortBy" json:"sort_by,omitempty"`
	// Filter is a regular expression used to filter which releases should be listed.
	//
	// Anything that matches the regexp will be included in the results.
	Filter string `protobuf:"bytes,4,opt,name=filter" json:"filter,omitempty"`
	// SortOrder is the ordering directive used for sorting.
	SortOrder ListSort_SortOrder `protobuf:"varint,5,opt,name=sort_order,json=sortOrder,enum=appscode.swift.v2.ListSort_SortOrder" json:"sort_order,omitempty"`
	// allowed values are UNKNOWN, DEPLOYED, DELETED, SUPERSEDED, FAILED, DELETING
	StatusCodes []string `protobuf:"bytes,6,rep,name=status_codes,json=statusCodes" json:"status_codes,omitempty"`
	// Namespace is the filter to select releases only from a specific namespace.
	Namespace string `protobuf:"bytes,7,opt,name=namespace" json:"namespace,omitempty"`
	// if true, list releases with all status codes
	All bool `protobuf:"varint,8,opt,name=all" json:"all,omitempty"`
}

func (m *SummarizeReleasesRequest) Reset()                    { *m = SummarizeReleasesRequest{} }
func (m *SummarizeReleasesRequest) String() string            { return proto.CompactTextString(m) }
func (*SummarizeReleasesRequest) ProtoMessage()               {}
func (*SummarizeReleasesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SummarizeReleasesRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *SummarizeReleasesRequest) GetOffset() string {
	if m != nil {
		return m.Offset
	}
	return ""
}

func (m *SummarizeReleasesRequest) GetSortBy() ListSort_SortBy {
	if m != nil {
		return m.SortBy
	}
	return ListSort_UNKNOWN
}

func (m *SummarizeReleasesRequest) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

func (m *SummarizeReleasesRequest) GetSortOrder() ListSort_SortOrder {
	if m != nil {
		return m.SortOrder
	}
	return ListSort_ASC
}

func (m *SummarizeReleasesRequest) GetStatusCodes() []string {
	if m != nil {
		return m.StatusCodes
	}
	return nil
}

func (m *SummarizeReleasesRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *SummarizeReleasesRequest) GetAll() bool {
	if m != nil {
		return m.All
	}
	return false
}

// ListSort defines sorting fields on a release list.
type ListSort struct {
}

func (m *ListSort) Reset()                    { *m = ListSort{} }
func (m *ListSort) String() string            { return proto.CompactTextString(m) }
func (*ListSort) ProtoMessage()               {}
func (*ListSort) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// @appscode
// SummarizeReleasesResponse is a list of release summaries.
type SummarizeReleasesResponse struct {
	Releases []*ReleaseSummary `protobuf:"bytes,4,rep,name=releases" json:"releases,omitempty"`
}

func (m *SummarizeReleasesResponse) Reset()                    { *m = SummarizeReleasesResponse{} }
func (m *SummarizeReleasesResponse) String() string            { return proto.CompactTextString(m) }
func (*SummarizeReleasesResponse) ProtoMessage()               {}
func (*SummarizeReleasesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SummarizeReleasesResponse) GetReleases() []*ReleaseSummary {
	if m != nil {
		return m.Releases
	}
	return nil
}

// ReleaseSummary summaries a deployment of a chart, together with the chart
// metadata and the variables used to deploy that chart.
type ReleaseSummary struct {
	// Name is the name of the release
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// Info provides information about a release
	Info *hapi_release4.Info `protobuf:"bytes,2,opt,name=info" json:"info,omitempty"`
	// ChartMetadata is the metadata of chart that was released.
	ChartMetadata *hapi_chart1.Metadata `protobuf:"bytes,3,opt,name=chart_metadata,json=chartMetadata" json:"chart_metadata,omitempty"`
	// Config is the set of extra Values added to the chart.
	// These values override the default values inside of the chart.
	Config *hapi_chart.Config `protobuf:"bytes,4,opt,name=config" json:"config,omitempty"`
	// Version is an int32 which represents the version of the release.
	Version int32 `protobuf:"varint,5,opt,name=version" json:"version,omitempty"`
	// Namespace is the kubernetes namespace of the release.
	Namespace string `protobuf:"bytes,6,opt,name=namespace" json:"namespace,omitempty"`
}

func (m *ReleaseSummary) Reset()                    { *m = ReleaseSummary{} }
func (m *ReleaseSummary) String() string            { return proto.CompactTextString(m) }
func (*ReleaseSummary) ProtoMessage()               {}
func (*ReleaseSummary) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReleaseSummary) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReleaseSummary) GetInfo() *hapi_release4.Info {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ReleaseSummary) GetChartMetadata() *hapi_chart1.Metadata {
	if m != nil {
		return m.ChartMetadata
	}
	return nil
}

func (m *ReleaseSummary) GetConfig() *hapi_chart.Config {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *ReleaseSummary) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ReleaseSummary) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

// GetReleaseStatusRequest is a request to get the status of a release.
type GetReleaseStatusRequest struct {
	// Name is the name of the release
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// Version is the version of the release
	Version int32 `protobuf:"varint,2,opt,name=version" json:"version,omitempty"`
}

func (m *GetReleaseStatusRequest) Reset()                    { *m = GetReleaseStatusRequest{} }
func (m *GetReleaseStatusRequest) String() string            { return proto.CompactTextString(m) }
func (*GetReleaseStatusRequest) ProtoMessage()               {}
func (*GetReleaseStatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetReleaseStatusRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetReleaseStatusRequest) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

// GetReleaseStatusResponse is the response indicating the status of the named release.
type GetReleaseStatusResponse struct {
	// Name is the name of the release.
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// Info contains information about the release.
	Info *hapi_release4.Info `protobuf:"bytes,2,opt,name=info" json:"info,omitempty"`
	// Namesapce the release was released into
	Namespace string `protobuf:"bytes,3,opt,name=namespace" json:"namespace,omitempty"`
}

func (m *GetReleaseStatusResponse) Reset()                    { *m = GetReleaseStatusResponse{} }
func (m *GetReleaseStatusResponse) String() string            { return proto.CompactTextString(m) }
func (*GetReleaseStatusResponse) ProtoMessage()               {}
func (*GetReleaseStatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetReleaseStatusResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetReleaseStatusResponse) GetInfo() *hapi_release4.Info {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *GetReleaseStatusResponse) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

// GetReleaseContentRequest is a request to get the contents of a release.
type GetReleaseContentRequest struct {
	// The name of the release
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// Version is the version of the release
	Version int32 `protobuf:"varint,2,opt,name=version" json:"version,omitempty"`
	// Format release config and values to JSON string
	FormatValuesAsJson bool `protobuf:"varint,3,opt,name=format_values_as_json,json=formatValuesAsJson" json:"format_values_as_json,omitempty"`
}

func (m *GetReleaseContentRequest) Reset()                    { *m = GetReleaseContentRequest{} }
func (m *GetReleaseContentRequest) String() string            { return proto.CompactTextString(m) }
func (*GetReleaseContentRequest) ProtoMessage()               {}
func (*GetReleaseContentRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GetReleaseContentRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetReleaseContentRequest) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *GetReleaseContentRequest) GetFormatValuesAsJson() bool {
	if m != nil {
		return m.FormatValuesAsJson
	}
	return false
}

// GetReleaseContentResponse is a response containing the contents of a release.
type GetReleaseContentResponse struct {
	// The release content
	Release *hapi_release5.Release `protobuf:"bytes,1,opt,name=release" json:"release,omitempty"`
}

func (m *GetReleaseContentResponse) Reset()                    { *m = GetReleaseContentResponse{} }
func (m *GetReleaseContentResponse) String() string            { return proto.CompactTextString(m) }
func (*GetReleaseContentResponse) ProtoMessage()               {}
func (*GetReleaseContentResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *GetReleaseContentResponse) GetRelease() *hapi_release5.Release {
	if m != nil {
		return m.Release
	}
	return nil
}

// UpdateReleaseRequest updates a release.
type UpdateReleaseRequest struct {
	// The name of the release
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// Chart is the protobuf representation of a chart.
	Chart *hapi_chart3.Chart `protobuf:"bytes,2,opt,name=chart" json:"chart,omitempty"`
	// Values is a string containing (unparsed) YAML values.
	Values *hapi_chart.Config `protobuf:"bytes,3,opt,name=values" json:"values,omitempty"`
	// dry_run, if true, will run through the release logic, but neither create
	DryRun bool `protobuf:"varint,4,opt,name=dry_run,json=dryRun" json:"dry_run,omitempty"`
	// DisableHooks causes the server to skip running any hooks for the upgrade.
	DisableHooks bool `protobuf:"varint,5,opt,name=disable_hooks,json=disableHooks" json:"disable_hooks,omitempty"`
	// Performs pods restart for resources if applicable
	Recreate bool `protobuf:"varint,6,opt,name=recreate" json:"recreate,omitempty"`
	// timeout specifies the max amount of time any kubernetes client command can run.
	Timeout int64 `protobuf:"varint,7,opt,name=timeout" json:"timeout,omitempty"`
	// ResetValues will cause Tiller to ignore stored values, resetting to default values.
	ResetValues bool `protobuf:"varint,8,opt,name=reset_values,json=resetValues" json:"reset_values,omitempty"`
	// wait, if true, will wait until all Pods, PVCs, and Services are in a ready state
	// before marking the release as successful. It will wait for as long as timeout
	Wait bool `protobuf:"varint,9,opt,name=wait" json:"wait,omitempty"`
	// ReuseValues will cause Tiller to reuse the values from the last release.
	// This is ignored if reset_values is set.
	ReuseValues bool `protobuf:"varint,10,opt,name=reuse_values,json=reuseValues" json:"reuse_values,omitempty"`
	// Force resource update through delete/recreate if needed.
	Force bool `protobuf:"varint,11,opt,name=force" json:"force,omitempty"`
	// URL to download chart archive
	ChartUrl string `protobuf:"bytes,12,opt,name=chart_url,json=chartUrl" json:"chart_url,omitempty"`
	// `ca_bundle` is a PEM encoded CA bundle used to sign server certificate of chart repository.
	// +optional
	CaBundle []byte `protobuf:"bytes,13,opt,name=ca_bundle,json=caBundle,proto3" json:"ca_bundle,omitempty"`
	// Username is the username for basic authentication to the chart repository.
	// +optional
	Username string `protobuf:"bytes,14,opt,name=username" json:"username,omitempty"`
	// Password is the password for basic authentication to the chart repository.
	// +optional
	Password string `protobuf:"bytes,15,opt,name=password" json:"password,omitempty"`
	// Token is the bearer token for authentication to the chart repository.
	// +optional
	Token string `protobuf:"bytes,16,opt,name=token" json:"token,omitempty"`
	// ClientCertificate contains PEM-encoded data passed as a client cert to chart repository.
	// +optional
	ClientCertificate []byte `protobuf:"bytes,17,opt,name=client_certificate,json=clientCertificate,proto3" json:"client_certificate,omitempty"`
	// ClientKey contains PEM-encoded data passed as a client key to chart repository.
	// +optional
	ClientKey []byte `protobuf:"bytes,18,opt,name=client_key,json=clientKey,proto3" json:"client_key,omitempty"`
	// Skip certificate verification for chart repository.
	// +optional
	InsecureSkipVerify bool `protobuf:"varint,19,opt,name=insecure_skip_verify,json=insecureSkipVerify" json:"insecure_skip_verify,omitempty"`
}

func (m *UpdateReleaseRequest) Reset()                    { *m = UpdateReleaseRequest{} }
func (m *UpdateReleaseRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateReleaseRequest) ProtoMessage()               {}
func (*UpdateReleaseRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *UpdateReleaseRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateReleaseRequest) GetChart() *hapi_chart3.Chart {
	if m != nil {
		return m.Chart
	}
	return nil
}

func (m *UpdateReleaseRequest) GetValues() *hapi_chart.Config {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *UpdateReleaseRequest) GetDryRun() bool {
	if m != nil {
		return m.DryRun
	}
	return false
}

func (m *UpdateReleaseRequest) GetDisableHooks() bool {
	if m != nil {
		return m.DisableHooks
	}
	return false
}

func (m *UpdateReleaseRequest) GetRecreate() bool {
	if m != nil {
		return m.Recreate
	}
	return false
}

func (m *UpdateReleaseRequest) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *UpdateReleaseRequest) GetResetValues() bool {
	if m != nil {
		return m.ResetValues
	}
	return false
}

func (m *UpdateReleaseRequest) GetWait() bool {
	if m != nil {
		return m.Wait
	}
	return false
}

func (m *UpdateReleaseRequest) GetReuseValues() bool {
	if m != nil {
		return m.ReuseValues
	}
	return false
}

func (m *UpdateReleaseRequest) GetForce() bool {
	if m != nil {
		return m.Force
	}
	return false
}

func (m *UpdateReleaseRequest) GetChartUrl() string {
	if m != nil {
		return m.ChartUrl
	}
	return ""
}

func (m *UpdateReleaseRequest) GetCaBundle() []byte {
	if m != nil {
		return m.CaBundle
	}
	return nil
}

func (m *UpdateReleaseRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UpdateReleaseRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UpdateReleaseRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *UpdateReleaseRequest) GetClientCertificate() []byte {
	if m != nil {
		return m.ClientCertificate
	}
	return nil
}

func (m *UpdateReleaseRequest) GetClientKey() []byte {
	if m != nil {
		return m.ClientKey
	}
	return nil
}

func (m *UpdateReleaseRequest) GetInsecureSkipVerify() bool {
	if m != nil {
		return m.InsecureSkipVerify
	}
	return false
}

// UpdateReleaseResponse is the response to an update request.
type UpdateReleaseResponse struct {
	Release *hapi_release5.Release `protobuf:"bytes,1,opt,name=release" json:"release,omitempty"`
}

func (m *UpdateReleaseResponse) Reset()                    { *m = UpdateReleaseResponse{} }
func (m *UpdateReleaseResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateReleaseResponse) ProtoMessage()               {}
func (*UpdateReleaseResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *UpdateReleaseResponse) GetRelease() *hapi_release5.Release {
	if m != nil {
		return m.Release
	}
	return nil
}

type RollbackReleaseRequest struct {
	// The name of the release
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// dry_run, if true, will run through the release logic but no create
	DryRun bool `protobuf:"varint,2,opt,name=dry_run,json=dryRun" json:"dry_run,omitempty"`
	// DisableHooks causes the server to skip running any hooks for the rollback
	DisableHooks bool `protobuf:"varint,3,opt,name=disable_hooks,json=disableHooks" json:"disable_hooks,omitempty"`
	// Version is the version of the release to deploy.
	Version int32 `protobuf:"varint,4,opt,name=version" json:"version,omitempty"`
	// Performs pods restart for resources if applicable
	Recreate bool `protobuf:"varint,5,opt,name=recreate" json:"recreate,omitempty"`
	// timeout specifies the max amount of time any kubernetes client command can run.
	Timeout int64 `protobuf:"varint,6,opt,name=timeout" json:"timeout,omitempty"`
	// wait, if true, will wait until all Pods, PVCs, and Services are in a ready state
	// before marking the release as successful. It will wait for as long as timeout
	Wait bool `protobuf:"varint,7,opt,name=wait" json:"wait,omitempty"`
	// Force resource update through delete/recreate if needed.
	Force bool `protobuf:"varint,8,opt,name=force" json:"force,omitempty"`
}

func (m *RollbackReleaseRequest) Reset()                    { *m = RollbackReleaseRequest{} }
func (m *RollbackReleaseRequest) String() string            { return proto.CompactTextString(m) }
func (*RollbackReleaseRequest) ProtoMessage()               {}
func (*RollbackReleaseRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *RollbackReleaseRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RollbackReleaseRequest) GetDryRun() bool {
	if m != nil {
		return m.DryRun
	}
	return false
}

func (m *RollbackReleaseRequest) GetDisableHooks() bool {
	if m != nil {
		return m.DisableHooks
	}
	return false
}

func (m *RollbackReleaseRequest) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *RollbackReleaseRequest) GetRecreate() bool {
	if m != nil {
		return m.Recreate
	}
	return false
}

func (m *RollbackReleaseRequest) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *RollbackReleaseRequest) GetWait() bool {
	if m != nil {
		return m.Wait
	}
	return false
}

func (m *RollbackReleaseRequest) GetForce() bool {
	if m != nil {
		return m.Force
	}
	return false
}

// RollbackReleaseResponse is the response to an update request.
type RollbackReleaseResponse struct {
	Release *hapi_release5.Release `protobuf:"bytes,1,opt,name=release" json:"release,omitempty"`
}

func (m *RollbackReleaseResponse) Reset()                    { *m = RollbackReleaseResponse{} }
func (m *RollbackReleaseResponse) String() string            { return proto.CompactTextString(m) }
func (*RollbackReleaseResponse) ProtoMessage()               {}
func (*RollbackReleaseResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *RollbackReleaseResponse) GetRelease() *hapi_release5.Release {
	if m != nil {
		return m.Release
	}
	return nil
}

// InstallReleaseRequest is the request for an installation of a chart.
type InstallReleaseRequest struct {
	// Chart is the protobuf representation of a chart.
	Chart *hapi_chart3.Chart `protobuf:"bytes,1,opt,name=chart" json:"chart,omitempty"`
	// Values is a string containing (unparsed) YAML values.
	Values *hapi_chart.Config `protobuf:"bytes,2,opt,name=values" json:"values,omitempty"`
	// DryRun, if true, will run through the release logic, but neither create
	// a release object nor deploy to Kubernetes. The release object returned
	// in the response will be fake.
	DryRun bool `protobuf:"varint,3,opt,name=dry_run,json=dryRun" json:"dry_run,omitempty"`
	// Name is the candidate release name. This must be unique to the
	// namespace, otherwise the server will return an error. If it is not
	// supplied, the server will autogenerate one.
	Name string `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	// DisableHooks causes the server to skip running any hooks for the install.
	DisableHooks bool `protobuf:"varint,5,opt,name=disable_hooks,json=disableHooks" json:"disable_hooks,omitempty"`
	// Namepace is the kubernetes namespace of the release.
	Namespace string `protobuf:"bytes,6,opt,name=namespace" json:"namespace,omitempty"`
	// ReuseName requests that Tiller re-uses a name, instead of erroring out.
	ReuseName bool `protobuf:"varint,7,opt,name=reuse_name,json=reuseName" json:"reuse_name,omitempty"`
	// timeout specifies the max amount of time any kubernetes client command can run.
	Timeout int64 `protobuf:"varint,8,opt,name=timeout" json:"timeout,omitempty"`
	// wait, if true, will wait until all Pods, PVCs, and Services are in a ready state
	// before marking the release as successful. It will wait for as long as timeout
	Wait bool `protobuf:"varint,9,opt,name=wait" json:"wait,omitempty"`
	// URL to download chart archive
	ChartUrl string `protobuf:"bytes,10,opt,name=chart_url,json=chartUrl" json:"chart_url,omitempty"`
	// `ca_bundle` is a PEM encoded CA bundle used to sign server certificate of chart repository.
	// +optional
	CaBundle []byte `protobuf:"bytes,11,opt,name=ca_bundle,json=caBundle,proto3" json:"ca_bundle,omitempty"`
	// Username is the username for basic authentication to the chart repository.
	// +optional
	Username string `protobuf:"bytes,12,opt,name=username" json:"username,omitempty"`
	// Password is the password for basic authentication to the chart repository.
	// +optional
	Password string `protobuf:"bytes,13,opt,name=password" json:"password,omitempty"`
	// Token is the bearer token for authentication to the chart repository.
	// +optional
	Token string `protobuf:"bytes,14,opt,name=token" json:"token,omitempty"`
	// ClientCertificate contains PEM-encoded data passed as a client cert to chart repository.
	// +optional
	ClientCertificate []byte `protobuf:"bytes,15,opt,name=client_certificate,json=clientCertificate,proto3" json:"client_certificate,omitempty"`
	// ClientKey contains PEM-encoded data passed as a client key to chart repository.
	// +optional
	ClientKey []byte `protobuf:"bytes,16,opt,name=client_key,json=clientKey,proto3" json:"client_key,omitempty"`
	// Skip certificate verification for chart repository.
	// +optional
	InsecureSkipVerify bool `protobuf:"varint,17,opt,name=insecure_skip_verify,json=insecureSkipVerify" json:"insecure_skip_verify,omitempty"`
}

func (m *InstallReleaseRequest) Reset()                    { *m = InstallReleaseRequest{} }
func (m *InstallReleaseRequest) String() string            { return proto.CompactTextString(m) }
func (*InstallReleaseRequest) ProtoMessage()               {}
func (*InstallReleaseRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *InstallReleaseRequest) GetChart() *hapi_chart3.Chart {
	if m != nil {
		return m.Chart
	}
	return nil
}

func (m *InstallReleaseRequest) GetValues() *hapi_chart.Config {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *InstallReleaseRequest) GetDryRun() bool {
	if m != nil {
		return m.DryRun
	}
	return false
}

func (m *InstallReleaseRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *InstallReleaseRequest) GetDisableHooks() bool {
	if m != nil {
		return m.DisableHooks
	}
	return false
}

func (m *InstallReleaseRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *InstallReleaseRequest) GetReuseName() bool {
	if m != nil {
		return m.ReuseName
	}
	return false
}

func (m *InstallReleaseRequest) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *InstallReleaseRequest) GetWait() bool {
	if m != nil {
		return m.Wait
	}
	return false
}

func (m *InstallReleaseRequest) GetChartUrl() string {
	if m != nil {
		return m.ChartUrl
	}
	return ""
}

func (m *InstallReleaseRequest) GetCaBundle() []byte {
	if m != nil {
		return m.CaBundle
	}
	return nil
}

func (m *InstallReleaseRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *InstallReleaseRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *InstallReleaseRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *InstallReleaseRequest) GetClientCertificate() []byte {
	if m != nil {
		return m.ClientCertificate
	}
	return nil
}

func (m *InstallReleaseRequest) GetClientKey() []byte {
	if m != nil {
		return m.ClientKey
	}
	return nil
}

func (m *InstallReleaseRequest) GetInsecureSkipVerify() bool {
	if m != nil {
		return m.InsecureSkipVerify
	}
	return false
}

// InstallReleaseResponse is the response from a release installation.
type InstallReleaseResponse struct {
	Release *hapi_release5.Release `protobuf:"bytes,1,opt,name=release" json:"release,omitempty"`
}

func (m *InstallReleaseResponse) Reset()                    { *m = InstallReleaseResponse{} }
func (m *InstallReleaseResponse) String() string            { return proto.CompactTextString(m) }
func (*InstallReleaseResponse) ProtoMessage()               {}
func (*InstallReleaseResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *InstallReleaseResponse) GetRelease() *hapi_release5.Release {
	if m != nil {
		return m.Release
	}
	return nil
}

// UninstallReleaseRequest represents a request to uninstall a named release.
type UninstallReleaseRequest struct {
	// Name is the name of the release to delete.
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// DisableHooks causes the server to skip running any hooks for the uninstall.
	DisableHooks bool `protobuf:"varint,2,opt,name=disable_hooks,json=disableHooks" json:"disable_hooks,omitempty"`
	// Purge removes the release from the store and make its name free for later use.
	Purge bool `protobuf:"varint,3,opt,name=purge" json:"purge,omitempty"`
	// timeout specifies the max amount of time any kubernetes client command can run.
	Timeout int64 `protobuf:"varint,4,opt,name=timeout" json:"timeout,omitempty"`
}

func (m *UninstallReleaseRequest) Reset()                    { *m = UninstallReleaseRequest{} }
func (m *UninstallReleaseRequest) String() string            { return proto.CompactTextString(m) }
func (*UninstallReleaseRequest) ProtoMessage()               {}
func (*UninstallReleaseRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *UninstallReleaseRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UninstallReleaseRequest) GetDisableHooks() bool {
	if m != nil {
		return m.DisableHooks
	}
	return false
}

func (m *UninstallReleaseRequest) GetPurge() bool {
	if m != nil {
		return m.Purge
	}
	return false
}

func (m *UninstallReleaseRequest) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

// UninstallReleaseResponse represents a successful response to an uninstall request.
type UninstallReleaseResponse struct {
	// Release is the release that was marked deleted.
	Release *hapi_release5.Release `protobuf:"bytes,1,opt,name=release" json:"release,omitempty"`
	// Info is an uninstall message
	Info string `protobuf:"bytes,2,opt,name=info" json:"info,omitempty"`
}

func (m *UninstallReleaseResponse) Reset()                    { *m = UninstallReleaseResponse{} }
func (m *UninstallReleaseResponse) String() string            { return proto.CompactTextString(m) }
func (*UninstallReleaseResponse) ProtoMessage()               {}
func (*UninstallReleaseResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *UninstallReleaseResponse) GetRelease() *hapi_release5.Release {
	if m != nil {
		return m.Release
	}
	return nil
}

func (m *UninstallReleaseResponse) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

// GetVersionRequest requests for version information.
type GetVersionRequest struct {
}

func (m *GetVersionRequest) Reset()                    { *m = GetVersionRequest{} }
func (m *GetVersionRequest) String() string            { return proto.CompactTextString(m) }
func (*GetVersionRequest) ProtoMessage()               {}
func (*GetVersionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

type GetVersionResponse struct {
	Version *hapi_version.Version `protobuf:"bytes,1,opt,name=Version" json:"Version,omitempty"`
}

func (m *GetVersionResponse) Reset()                    { *m = GetVersionResponse{} }
func (m *GetVersionResponse) String() string            { return proto.CompactTextString(m) }
func (*GetVersionResponse) ProtoMessage()               {}
func (*GetVersionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *GetVersionResponse) GetVersion() *hapi_version.Version {
	if m != nil {
		return m.Version
	}
	return nil
}

// GetHistoryRequest requests a release's history.
type GetHistoryRequest struct {
	// The name of the release.
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// The maximum number of releases to include.
	Max int32 `protobuf:"varint,2,opt,name=max" json:"max,omitempty"`
}

func (m *GetHistoryRequest) Reset()                    { *m = GetHistoryRequest{} }
func (m *GetHistoryRequest) String() string            { return proto.CompactTextString(m) }
func (*GetHistoryRequest) ProtoMessage()               {}
func (*GetHistoryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *GetHistoryRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetHistoryRequest) GetMax() int32 {
	if m != nil {
		return m.Max
	}
	return 0
}

// GetHistoryResponse is received in response to a GetHistory rpc.
type GetHistoryResponse struct {
	Releases []*hapi_release5.Release `protobuf:"bytes,1,rep,name=releases" json:"releases,omitempty"`
}

func (m *GetHistoryResponse) Reset()                    { *m = GetHistoryResponse{} }
func (m *GetHistoryResponse) String() string            { return proto.CompactTextString(m) }
func (*GetHistoryResponse) ProtoMessage()               {}
func (*GetHistoryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *GetHistoryResponse) GetReleases() []*hapi_release5.Release {
	if m != nil {
		return m.Releases
	}
	return nil
}

func init() {
	proto.RegisterType((*SummarizeReleasesRequest)(nil), "appscode.swift.v2.SummarizeReleasesRequest")
	proto.RegisterType((*ListSort)(nil), "appscode.swift.v2.ListSort")
	proto.RegisterType((*SummarizeReleasesResponse)(nil), "appscode.swift.v2.SummarizeReleasesResponse")
	proto.RegisterType((*ReleaseSummary)(nil), "appscode.swift.v2.ReleaseSummary")
	proto.RegisterType((*GetReleaseStatusRequest)(nil), "appscode.swift.v2.GetReleaseStatusRequest")
	proto.RegisterType((*GetReleaseStatusResponse)(nil), "appscode.swift.v2.GetReleaseStatusResponse")
	proto.RegisterType((*GetReleaseContentRequest)(nil), "appscode.swift.v2.GetReleaseContentRequest")
	proto.RegisterType((*GetReleaseContentResponse)(nil), "appscode.swift.v2.GetReleaseContentResponse")
	proto.RegisterType((*UpdateReleaseRequest)(nil), "appscode.swift.v2.UpdateReleaseRequest")
	proto.RegisterType((*UpdateReleaseResponse)(nil), "appscode.swift.v2.UpdateReleaseResponse")
	proto.RegisterType((*RollbackReleaseRequest)(nil), "appscode.swift.v2.RollbackReleaseRequest")
	proto.RegisterType((*RollbackReleaseResponse)(nil), "appscode.swift.v2.RollbackReleaseResponse")
	proto.RegisterType((*InstallReleaseRequest)(nil), "appscode.swift.v2.InstallReleaseRequest")
	proto.RegisterType((*InstallReleaseResponse)(nil), "appscode.swift.v2.InstallReleaseResponse")
	proto.RegisterType((*UninstallReleaseRequest)(nil), "appscode.swift.v2.UninstallReleaseRequest")
	proto.RegisterType((*UninstallReleaseResponse)(nil), "appscode.swift.v2.UninstallReleaseResponse")
	proto.RegisterType((*GetVersionRequest)(nil), "appscode.swift.v2.GetVersionRequest")
	proto.RegisterType((*GetVersionResponse)(nil), "appscode.swift.v2.GetVersionResponse")
	proto.RegisterType((*GetHistoryRequest)(nil), "appscode.swift.v2.GetHistoryRequest")
	proto.RegisterType((*GetHistoryResponse)(nil), "appscode.swift.v2.GetHistoryResponse")
	proto.RegisterEnum("appscode.swift.v2.ListSort_SortBy", ListSort_SortBy_name, ListSort_SortBy_value)
	proto.RegisterEnum("appscode.swift.v2.ListSort_SortOrder", ListSort_SortOrder_name, ListSort_SortOrder_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ReleaseService service

type ReleaseServiceClient interface {
	// SummarizeReleases retrieves summary of release history.
	// TODO: Allow filtering the set of releases by
	// release status. By default, SummarizeReleases returns the releases who
	// current status is "Active".
	SummarizeReleases(ctx context.Context, in *SummarizeReleasesRequest, opts ...grpc.CallOption) (*SummarizeReleasesResponse, error)
	// GetReleasesStatus retrieves status information for the specified release.
	GetReleaseStatus(ctx context.Context, in *GetReleaseStatusRequest, opts ...grpc.CallOption) (*GetReleaseStatusResponse, error)
	// GetReleaseContent retrieves the release content (chart + value) for the specified release.
	GetReleaseContent(ctx context.Context, in *GetReleaseContentRequest, opts ...grpc.CallOption) (*GetReleaseContentResponse, error)
	// UpdateRelease updates release content.
	UpdateRelease(ctx context.Context, in *UpdateReleaseRequest, opts ...grpc.CallOption) (*UpdateReleaseResponse, error)
	// InstallRelease requests installation of a chart as a new release.
	InstallRelease(ctx context.Context, in *InstallReleaseRequest, opts ...grpc.CallOption) (*InstallReleaseResponse, error)
	// UninstallRelease requests deletion of a named release.
	UninstallRelease(ctx context.Context, in *UninstallReleaseRequest, opts ...grpc.CallOption) (*UninstallReleaseResponse, error)
	// GetVersion returns the current version of the server.
	GetVersion(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*GetVersionResponse, error)
	// RollbackRelease rolls back a release to a previous version.
	RollbackRelease(ctx context.Context, in *RollbackReleaseRequest, opts ...grpc.CallOption) (*RollbackReleaseResponse, error)
	// ReleaseHistory retrieves a releasse's history.
	GetHistory(ctx context.Context, in *GetHistoryRequest, opts ...grpc.CallOption) (*GetHistoryResponse, error)
}

type releaseServiceClient struct {
	cc *grpc.ClientConn
}

func NewReleaseServiceClient(cc *grpc.ClientConn) ReleaseServiceClient {
	return &releaseServiceClient{cc}
}

func (c *releaseServiceClient) SummarizeReleases(ctx context.Context, in *SummarizeReleasesRequest, opts ...grpc.CallOption) (*SummarizeReleasesResponse, error) {
	out := new(SummarizeReleasesResponse)
	err := grpc.Invoke(ctx, "/appscode.swift.v2.ReleaseService/SummarizeReleases", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *releaseServiceClient) GetReleaseStatus(ctx context.Context, in *GetReleaseStatusRequest, opts ...grpc.CallOption) (*GetReleaseStatusResponse, error) {
	out := new(GetReleaseStatusResponse)
	err := grpc.Invoke(ctx, "/appscode.swift.v2.ReleaseService/GetReleaseStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *releaseServiceClient) GetReleaseContent(ctx context.Context, in *GetReleaseContentRequest, opts ...grpc.CallOption) (*GetReleaseContentResponse, error) {
	out := new(GetReleaseContentResponse)
	err := grpc.Invoke(ctx, "/appscode.swift.v2.ReleaseService/GetReleaseContent", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *releaseServiceClient) UpdateRelease(ctx context.Context, in *UpdateReleaseRequest, opts ...grpc.CallOption) (*UpdateReleaseResponse, error) {
	out := new(UpdateReleaseResponse)
	err := grpc.Invoke(ctx, "/appscode.swift.v2.ReleaseService/UpdateRelease", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *releaseServiceClient) InstallRelease(ctx context.Context, in *InstallReleaseRequest, opts ...grpc.CallOption) (*InstallReleaseResponse, error) {
	out := new(InstallReleaseResponse)
	err := grpc.Invoke(ctx, "/appscode.swift.v2.ReleaseService/InstallRelease", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *releaseServiceClient) UninstallRelease(ctx context.Context, in *UninstallReleaseRequest, opts ...grpc.CallOption) (*UninstallReleaseResponse, error) {
	out := new(UninstallReleaseResponse)
	err := grpc.Invoke(ctx, "/appscode.swift.v2.ReleaseService/UninstallRelease", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *releaseServiceClient) GetVersion(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*GetVersionResponse, error) {
	out := new(GetVersionResponse)
	err := grpc.Invoke(ctx, "/appscode.swift.v2.ReleaseService/GetVersion", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *releaseServiceClient) RollbackRelease(ctx context.Context, in *RollbackReleaseRequest, opts ...grpc.CallOption) (*RollbackReleaseResponse, error) {
	out := new(RollbackReleaseResponse)
	err := grpc.Invoke(ctx, "/appscode.swift.v2.ReleaseService/RollbackRelease", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *releaseServiceClient) GetHistory(ctx context.Context, in *GetHistoryRequest, opts ...grpc.CallOption) (*GetHistoryResponse, error) {
	out := new(GetHistoryResponse)
	err := grpc.Invoke(ctx, "/appscode.swift.v2.ReleaseService/GetHistory", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ReleaseService service

type ReleaseServiceServer interface {
	// SummarizeReleases retrieves summary of release history.
	// TODO: Allow filtering the set of releases by
	// release status. By default, SummarizeReleases returns the releases who
	// current status is "Active".
	SummarizeReleases(context.Context, *SummarizeReleasesRequest) (*SummarizeReleasesResponse, error)
	// GetReleasesStatus retrieves status information for the specified release.
	GetReleaseStatus(context.Context, *GetReleaseStatusRequest) (*GetReleaseStatusResponse, error)
	// GetReleaseContent retrieves the release content (chart + value) for the specified release.
	GetReleaseContent(context.Context, *GetReleaseContentRequest) (*GetReleaseContentResponse, error)
	// UpdateRelease updates release content.
	UpdateRelease(context.Context, *UpdateReleaseRequest) (*UpdateReleaseResponse, error)
	// InstallRelease requests installation of a chart as a new release.
	InstallRelease(context.Context, *InstallReleaseRequest) (*InstallReleaseResponse, error)
	// UninstallRelease requests deletion of a named release.
	UninstallRelease(context.Context, *UninstallReleaseRequest) (*UninstallReleaseResponse, error)
	// GetVersion returns the current version of the server.
	GetVersion(context.Context, *GetVersionRequest) (*GetVersionResponse, error)
	// RollbackRelease rolls back a release to a previous version.
	RollbackRelease(context.Context, *RollbackReleaseRequest) (*RollbackReleaseResponse, error)
	// ReleaseHistory retrieves a releasse's history.
	GetHistory(context.Context, *GetHistoryRequest) (*GetHistoryResponse, error)
}

func RegisterReleaseServiceServer(s *grpc.Server, srv ReleaseServiceServer) {
	s.RegisterService(&_ReleaseService_serviceDesc, srv)
}

func _ReleaseService_SummarizeReleases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SummarizeReleasesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReleaseServiceServer).SummarizeReleases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appscode.swift.v2.ReleaseService/SummarizeReleases",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReleaseServiceServer).SummarizeReleases(ctx, req.(*SummarizeReleasesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReleaseService_GetReleaseStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReleaseStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReleaseServiceServer).GetReleaseStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appscode.swift.v2.ReleaseService/GetReleaseStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReleaseServiceServer).GetReleaseStatus(ctx, req.(*GetReleaseStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReleaseService_GetReleaseContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReleaseContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReleaseServiceServer).GetReleaseContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appscode.swift.v2.ReleaseService/GetReleaseContent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReleaseServiceServer).GetReleaseContent(ctx, req.(*GetReleaseContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReleaseService_UpdateRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReleaseServiceServer).UpdateRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appscode.swift.v2.ReleaseService/UpdateRelease",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReleaseServiceServer).UpdateRelease(ctx, req.(*UpdateReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReleaseService_InstallRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstallReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReleaseServiceServer).InstallRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appscode.swift.v2.ReleaseService/InstallRelease",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReleaseServiceServer).InstallRelease(ctx, req.(*InstallReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReleaseService_UninstallRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UninstallReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReleaseServiceServer).UninstallRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appscode.swift.v2.ReleaseService/UninstallRelease",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReleaseServiceServer).UninstallRelease(ctx, req.(*UninstallReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReleaseService_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReleaseServiceServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appscode.swift.v2.ReleaseService/GetVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReleaseServiceServer).GetVersion(ctx, req.(*GetVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReleaseService_RollbackRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReleaseServiceServer).RollbackRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appscode.swift.v2.ReleaseService/RollbackRelease",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReleaseServiceServer).RollbackRelease(ctx, req.(*RollbackReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReleaseService_GetHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReleaseServiceServer).GetHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appscode.swift.v2.ReleaseService/GetHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReleaseServiceServer).GetHistory(ctx, req.(*GetHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ReleaseService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "appscode.swift.v2.ReleaseService",
	HandlerType: (*ReleaseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SummarizeReleases",
			Handler:    _ReleaseService_SummarizeReleases_Handler,
		},
		{
			MethodName: "GetReleaseStatus",
			Handler:    _ReleaseService_GetReleaseStatus_Handler,
		},
		{
			MethodName: "GetReleaseContent",
			Handler:    _ReleaseService_GetReleaseContent_Handler,
		},
		{
			MethodName: "UpdateRelease",
			Handler:    _ReleaseService_UpdateRelease_Handler,
		},
		{
			MethodName: "InstallRelease",
			Handler:    _ReleaseService_InstallRelease_Handler,
		},
		{
			MethodName: "UninstallRelease",
			Handler:    _ReleaseService_UninstallRelease_Handler,
		},
		{
			MethodName: "GetVersion",
			Handler:    _ReleaseService_GetVersion_Handler,
		},
		{
			MethodName: "RollbackRelease",
			Handler:    _ReleaseService_RollbackRelease_Handler,
		},
		{
			MethodName: "GetHistory",
			Handler:    _ReleaseService_GetHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tiller.proto",
}

func init() { proto.RegisterFile("tiller.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1561 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x58, 0x4b, 0x73, 0x1b, 0xc5,
	0x13, 0xff, 0xaf, 0x24, 0xeb, 0xd1, 0xb2, 0x1d, 0x69, 0xe2, 0xc7, 0x5a, 0xff, 0x10, 0x9c, 0x25,
	0x0f, 0xc5, 0x21, 0x72, 0x22, 0x1e, 0x55, 0x90, 0xe2, 0x60, 0x3b, 0x2e, 0xe7, 0xe1, 0x38, 0xa9,
	0x35, 0x0e, 0x55, 0x39, 0xa0, 0x5a, 0xaf, 0x46, 0xce, 0xe2, 0xd5, 0x8e, 0x98, 0x99, 0x75, 0x10,
	0x29, 0xaa, 0xa8, 0x9c, 0xb8, 0x43, 0x41, 0x15, 0x27, 0x38, 0xf0, 0x01, 0x38, 0xc0, 0x17, 0xe1,
	0x2b, 0xe4, 0x46, 0x71, 0xe3, 0x03, 0x50, 0x3b, 0x0f, 0x79, 0x57, 0x5e, 0xc9, 0xc2, 0x5c, 0xa4,
	0x9d, 0xe9, 0xee, 0xe9, 0x5f, 0x77, 0xff, 0x7a, 0xd4, 0x2b, 0x98, 0xe6, 0x9e, 0xef, 0x63, 0xda,
	0xe8, 0x51, 0xc2, 0x09, 0xaa, 0x3a, 0xbd, 0x1e, 0x73, 0x49, 0x1b, 0x37, 0xd8, 0x0b, 0xaf, 0xc3,
	0x1b, 0x47, 0xcd, 0xda, 0xc2, 0x73, 0xa7, 0xe7, 0xad, 0xba, 0xcf, 0x1d, 0xca, 0xe5, 0xa7, 0x54,
	0xad, 0x2d, 0xc6, 0xf7, 0x49, 0xd0, 0xf1, 0x0e, 0x94, 0x60, 0x29, 0x26, 0xe8, 0x62, 0xee, 0xb4,
	0x1d, 0xee, 0x28, 0x51, 0x4d, 0x88, 0x28, 0xf6, 0xb1, 0xc3, 0xb0, 0xfe, 0x4e, 0x9c, 0xa7, 0x65,
	0x5e, 0xd0, 0x21, 0x89, 0xf3, 0xb4, 0x80, 0x71, 0x87, 0x87, 0x2c, 0x71, 0xde, 0x11, 0xa6, 0xcc,
	0x23, 0x81, 0xfe, 0x56, 0xb2, 0x0b, 0x07, 0x84, 0x1c, 0xf8, 0x78, 0x35, 0xd2, 0x70, 0x82, 0x80,
	0x70, 0x87, 0x7b, 0x24, 0xd0, 0x96, 0x17, 0x75, 0xa0, 0xe9, 0x72, 0xeb, 0xf7, 0x0c, 0x98, 0xbb,
	0x61, 0xb7, 0xeb, 0x50, 0xef, 0x4b, 0x6c, 0x4b, 0xdf, 0xcc, 0xc6, 0x9f, 0x87, 0x98, 0x71, 0x34,
	0x07, 0x53, 0xbe, 0xd7, 0xf5, 0xb8, 0x69, 0x2c, 0x1b, 0xf5, 0xac, 0x2d, 0x17, 0x68, 0x01, 0xf2,
	0xa4, 0xd3, 0x61, 0x98, 0x9b, 0x99, 0x65, 0xa3, 0x5e, 0xb2, 0xd5, 0x0a, 0xdd, 0x81, 0x02, 0x23,
	0x94, 0xb7, 0xf6, 0xfb, 0x66, 0x76, 0xd9, 0xa8, 0xcf, 0x36, 0xad, 0xc6, 0x89, 0x2c, 0x37, 0xb6,
	0x3d, 0xc6, 0x77, 0x09, 0xe5, 0x8d, 0xe8, 0x63, 0xbd, 0x6f, 0xe7, 0x99, 0xf8, 0x8e, 0x0e, 0xed,
	0x78, 0x3e, 0xc7, 0xd4, 0xcc, 0xc9, 0x43, 0xe5, 0x0a, 0xdd, 0x05, 0x10, 0x87, 0x12, 0xda, 0xc6,
	0xd4, 0x9c, 0x12, 0xe7, 0x5e, 0x39, 0xed, 0xdc, 0xc7, 0x91, 0xb2, 0x5d, 0x62, 0xfa, 0x11, 0x5d,
	0x82, 0x69, 0x99, 0xcf, 0x56, 0x64, 0xc5, 0xcc, 0xfc, 0x72, 0xb6, 0x5e, 0xb2, 0xcb, 0x72, 0x6f,
	0x23, 0xda, 0x42, 0x17, 0xa0, 0x14, 0x38, 0x5d, 0xcc, 0x7a, 0x8e, 0x8b, 0xcd, 0x82, 0xc0, 0x70,
	0xbc, 0x81, 0x2a, 0x90, 0x75, 0x7c, 0xdf, 0x2c, 0x2e, 0x1b, 0xf5, 0xa2, 0x1d, 0x3d, 0x5a, 0x9f,
	0x42, 0x51, 0xfb, 0xb4, 0x9a, 0x90, 0x97, 0xe1, 0xa0, 0x32, 0x14, 0xf6, 0x76, 0x1e, 0xee, 0x3c,
	0xfe, 0x64, 0xa7, 0xf2, 0x3f, 0x54, 0x84, 0xdc, 0xce, 0xda, 0xa3, 0xcd, 0x8a, 0x81, 0xaa, 0x30,
	0xb3, 0xbd, 0xb6, 0xfb, 0x71, 0xcb, 0xde, 0xdc, 0xde, 0x5c, 0xdb, 0xdd, 0xbc, 0x5b, 0xc9, 0x58,
	0x17, 0xa1, 0x34, 0x80, 0x8a, 0x0a, 0x90, 0x5d, 0xdb, 0xdd, 0x90, 0x26, 0x77, 0x37, 0x77, 0x37,
	0x2a, 0x86, 0xf5, 0x0c, 0x96, 0x52, 0xea, 0xc2, 0x7a, 0x24, 0x60, 0x18, 0x7d, 0x04, 0x45, 0xc5,
	0x13, 0x66, 0xe6, 0x96, 0xb3, 0xf5, 0x72, 0xf3, 0x52, 0x4a, 0x4e, 0x94, 0x99, 0x3c, 0xa6, 0x6f,
	0x0f, 0x4c, 0xac, 0xbf, 0x0c, 0x98, 0x4d, 0x0a, 0x11, 0x82, 0x5c, 0x14, 0xad, 0xa8, 0x74, 0xc9,
	0x16, 0xcf, 0xe8, 0x2a, 0xe4, 0x22, 0x7a, 0x8a, 0x32, 0x97, 0x9b, 0xa8, 0x11, 0x91, 0xb0, 0xa1,
	0xc9, 0x7c, 0x3f, 0xe8, 0x10, 0x5b, 0xc8, 0xd1, 0x1d, 0x98, 0x15, 0x5d, 0xd0, 0xd2, 0x5d, 0x20,
	0xea, 0x5f, 0x6e, 0xce, 0x49, 0x0b, 0xd9, 0x4c, 0x8f, 0x94, 0xcc, 0x9e, 0x11, 0x6b, 0xbd, 0x44,
	0x2b, 0x90, 0x97, 0x5d, 0x25, 0x0a, 0x3f, 0x70, 0x23, 0x8d, 0x36, 0x84, 0xc4, 0x56, 0x1a, 0xc8,
	0x84, 0x82, 0xe2, 0xbe, 0x60, 0xc2, 0x94, 0xad, 0x97, 0xc9, 0xea, 0xe5, 0x87, 0xaa, 0x67, 0x6d,
	0xc1, 0xe2, 0x16, 0xe6, 0x3a, 0x62, 0x51, 0x74, 0x4d, 0xf1, 0xb4, 0xb8, 0x63, 0x6e, 0x32, 0x09,
	0x37, 0x16, 0x07, 0xf3, 0xe4, 0x41, 0xaa, 0x26, 0xff, 0x25, 0x83, 0x09, 0xf8, 0xd9, 0x61, 0xf8,
	0x2f, 0xe3, 0x5e, 0x37, 0x48, 0xc0, 0x71, 0xc0, 0xcf, 0x84, 0x1f, 0xdd, 0x86, 0xf9, 0x0e, 0xa1,
	0x5d, 0x87, 0xb7, 0x8e, 0x1c, 0x3f, 0xc4, 0xac, 0xe5, 0xb0, 0xd6, 0x67, 0x8c, 0x04, 0xc2, 0x67,
	0xd1, 0x46, 0x52, 0xf8, 0x54, 0xc8, 0xd6, 0xd8, 0x03, 0x46, 0x02, 0x6b, 0x1b, 0x96, 0x52, 0x9c,
	0xab, 0x98, 0x57, 0xa1, 0xa0, 0xa2, 0x11, 0x00, 0xca, 0xcd, 0xf9, 0x64, 0x88, 0xca, 0xcc, 0xd6,
	0x5a, 0xd6, 0x9f, 0x39, 0x98, 0xdb, 0xeb, 0xb5, 0x1d, 0xae, 0x39, 0x3d, 0x2e, 0x8e, 0x6b, 0x30,
	0x25, 0x68, 0xa0, 0xd2, 0x57, 0x4d, 0x30, 0x23, 0xfa, 0xb4, 0xa5, 0x3c, 0xe2, 0x90, 0x8c, 0x47,
	0x11, 0x2f, 0x95, 0x43, 0x52, 0x03, 0x2d, 0x42, 0xa1, 0x4d, 0xfb, 0x2d, 0x1a, 0x06, 0x82, 0x70,
	0x45, 0x3b, 0xdf, 0xa6, 0x7d, 0x3b, 0x0c, 0xd0, 0x5b, 0x30, 0xd3, 0xf6, 0x98, 0xb3, 0xef, 0xe3,
	0xd6, 0x73, 0x42, 0x0e, 0x99, 0xa0, 0x58, 0xd1, 0x9e, 0x56, 0x9b, 0xf7, 0xa2, 0x3d, 0x54, 0x8b,
	0x1a, 0xcf, 0xa5, 0xd8, 0xe1, 0x92, 0x66, 0x45, 0x7b, 0xb0, 0x8e, 0xd2, 0xce, 0xbd, 0x2e, 0x26,
	0x21, 0x17, 0xf7, 0x47, 0xd6, 0xd6, 0xcb, 0xe8, 0xfa, 0xa1, 0x98, 0x61, 0x9d, 0x75, 0x75, 0x8d,
	0x94, 0xc5, 0x9e, 0x4c, 0x76, 0x14, 0xff, 0x0b, 0xc7, 0xe3, 0x66, 0x49, 0x88, 0xc4, 0xb3, 0x34,
	0x0b, 0x19, 0xd6, 0x66, 0xa0, 0xcd, 0x42, 0x86, 0x95, 0xd9, 0x1c, 0x4c, 0x75, 0x08, 0x75, 0xb1,
	0x59, 0x16, 0x32, 0xb9, 0x40, 0xff, 0x87, 0x92, 0x6c, 0xc8, 0x90, 0xfa, 0xe6, 0xb4, 0xc8, 0x68,
	0x51, 0x6c, 0xec, 0x51, 0x5f, 0x08, 0x9d, 0xd6, 0x7e, 0x18, 0xb4, 0x7d, 0x6c, 0xce, 0x2c, 0x1b,
	0xf5, 0x69, 0xbb, 0xe8, 0x3a, 0xeb, 0x62, 0x1d, 0xc5, 0x17, 0x32, 0x4c, 0x45, 0x29, 0x66, 0xa5,
	0xa1, 0x5e, 0x47, 0xb2, 0x9e, 0xc3, 0xd8, 0x0b, 0x42, 0xdb, 0xe6, 0x39, 0x29, 0xd3, 0xeb, 0x08,
	0x07, 0x27, 0x87, 0x38, 0x30, 0x2b, 0x42, 0x20, 0x17, 0xe8, 0x26, 0x20, 0xd7, 0xf7, 0x70, 0xc0,
	0x5b, 0x2e, 0xa6, 0xdc, 0xeb, 0x78, 0x6e, 0x94, 0xb7, 0xaa, 0xf0, 0x59, 0x95, 0x92, 0x8d, 0x63,
	0x01, 0x7a, 0x03, 0x40, 0xa9, 0x1f, 0xe2, 0xbe, 0x89, 0x84, 0x5a, 0x49, 0xee, 0x3c, 0xc4, 0x7d,
	0x74, 0x0b, 0xe6, 0xbc, 0x80, 0x61, 0x37, 0xa4, 0xb8, 0xc5, 0x0e, 0xbd, 0x5e, 0xeb, 0x08, 0x53,
	0xaf, 0xd3, 0x37, 0xcf, 0x4b, 0xee, 0x6a, 0xd9, 0xee, 0xa1, 0xd7, 0x7b, 0x2a, 0x24, 0xd6, 0x3d,
	0x98, 0x1f, 0x22, 0xdb, 0x59, 0x79, 0xfb, 0xda, 0x80, 0x05, 0x9b, 0xf8, 0xfe, 0xbe, 0xe3, 0x1e,
	0x4e, 0xc0, 0xdc, 0x18, 0xc9, 0x32, 0xe3, 0x49, 0x96, 0x4d, 0x21, 0x59, 0xac, 0x7f, 0x73, 0xc9,
	0xfe, 0x8d, 0xd3, 0x6f, 0x6a, 0x34, 0xfd, 0xf2, 0x49, 0xfa, 0x69, 0x6e, 0x15, 0x62, 0xdc, 0x1a,
	0x10, 0xa7, 0x18, 0x23, 0x8e, 0xf5, 0x00, 0x16, 0x4f, 0x44, 0x79, 0xd6, 0x94, 0xfd, 0x9a, 0x83,
	0xf9, 0xfb, 0x01, 0xe3, 0x8e, 0xef, 0x0f, 0x65, 0x6c, 0xd0, 0xd7, 0xc6, 0xc4, 0x7d, 0x9d, 0xf9,
	0x37, 0x7d, 0x9d, 0x4d, 0xa4, 0x5c, 0xd7, 0x27, 0x17, 0xab, 0xcf, 0x44, 0xbd, 0x3e, 0xf6, 0x37,
	0x25, 0x22, 0xab, 0x6c, 0x4e, 0x71, 0xb8, 0x4c, 0x6d, 0x49, 0xec, 0xec, 0xa8, 0x3b, 0x58, 0x57,
	0xa3, 0x98, 0x5e, 0x8d, 0x78, 0xa7, 0x27, 0x1a, 0x16, 0xc6, 0x35, 0x6c, 0x79, 0x4c, 0xc3, 0x4e,
	0x8f, 0x69, 0xd8, 0x99, 0x51, 0x0d, 0x3b, 0x7b, 0x7a, 0xc3, 0x9e, 0x9b, 0xac, 0x61, 0x2b, 0x93,
	0x36, 0x6c, 0x75, 0x64, 0xc3, 0xde, 0x87, 0x85, 0x61, 0xca, 0x9c, 0x95, 0x7e, 0xaf, 0x0c, 0x58,
	0xdc, 0x0b, 0xbc, 0x54, 0x02, 0xa6, 0xb5, 0xec, 0x09, 0x4a, 0x64, 0x52, 0x28, 0x31, 0x07, 0x53,
	0xbd, 0x90, 0x1e, 0x60, 0x45, 0x31, 0xb9, 0x88, 0xd7, 0x3a, 0x97, 0xa8, 0xb5, 0xd5, 0x02, 0xf3,
	0x24, 0x86, 0x33, 0x46, 0x14, 0xa1, 0x1e, 0x0c, 0x13, 0x25, 0x39, 0x38, 0x58, 0xe7, 0xa1, 0xba,
	0x85, 0xf9, 0x53, 0x79, 0x3d, 0xa8, 0xf0, 0xac, 0x4d, 0x40, 0xf1, 0xcd, 0x63, 0x7f, 0x6a, 0x2b,
	0xe9, 0x4f, 0xbf, 0x4d, 0x68, 0x7d, 0xad, 0x65, 0x7d, 0x20, 0xce, 0xbe, 0xe7, 0x31, 0x4e, 0x68,
	0x7f, 0x5c, 0xea, 0x2a, 0x90, 0xed, 0x3a, 0x5f, 0xa8, 0x59, 0x23, 0x7a, 0xb4, 0xb6, 0x04, 0x82,
	0x81, 0xa9, 0x42, 0x70, 0x3b, 0x36, 0xb5, 0x1a, 0x62, 0x6a, 0x1d, 0x11, 0xf2, 0x40, 0xad, 0xf9,
	0x37, 0x1c, 0x4f, 0xaa, 0x98, 0x1e, 0x79, 0x2e, 0x46, 0xdf, 0x1b, 0x50, 0x3d, 0x31, 0x19, 0xa3,
	0x1b, 0x29, 0xf3, 0xef, 0xa8, 0xf7, 0x9a, 0xda, 0xdb, 0x93, 0x29, 0x4b, 0xd8, 0xd6, 0xd5, 0x57,
	0xbf, 0x99, 0x99, 0xa2, 0xf1, 0xea, 0x8f, 0xd7, 0xdf, 0x66, 0x6a, 0xc8, 0x5c, 0x95, 0x2f, 0x92,
	0xab, 0x47, 0x4d, 0xfd, 0xae, 0xc6, 0x56, 0xa3, 0x19, 0x0a, 0xfd, 0x6c, 0x40, 0x65, 0x78, 0x3a,
	0x44, 0x2b, 0x29, 0xae, 0x46, 0xcc, 0xa2, 0xb5, 0x1b, 0x13, 0xe9, 0x2a, 0x54, 0xef, 0xc6, 0x50,
	0xd5, 0xd1, 0xd5, 0x34, 0x54, 0x2f, 0xa3, 0xea, 0x7c, 0xa5, 0xde, 0x24, 0x25, 0xc6, 0x5f, 0x0c,
	0x51, 0xd4, 0xe4, 0x38, 0x87, 0xc6, 0x3b, 0x4e, 0x4e, 0x9c, 0xa9, 0xc9, 0x1b, 0x39, 0x21, 0x5a,
	0xef, 0xc5, 0x60, 0x5e, 0x47, 0xd7, 0xc6, 0xc0, 0x74, 0xa5, 0xa5, 0xc4, 0xf9, 0x9d, 0x01, 0x33,
	0x89, 0x9f, 0x6e, 0x74, 0x2d, 0xc5, 0x6d, 0xda, 0x24, 0x59, 0xab, 0x9f, 0xae, 0xa8, 0xb0, 0xdd,
	0x8a, 0x61, 0xbb, 0x5c, 0x7b, 0x73, 0x0c, 0xb6, 0x08, 0xd3, 0x87, 0xc6, 0x0a, 0xfa, 0xc1, 0x80,
	0xd9, 0xe4, 0x05, 0x85, 0xd2, 0xdc, 0xa5, 0xfe, 0xec, 0xd5, 0xae, 0x4f, 0xa0, 0x99, 0x86, 0xcc,
	0x9a, 0x04, 0xd9, 0x8f, 0x06, 0x54, 0x86, 0xaf, 0x9a, 0x54, 0xf2, 0x8d, 0xb8, 0x13, 0x53, 0xc9,
	0x37, 0xea, 0xee, 0xb2, 0x6e, 0xc6, 0xf0, 0x5d, 0x5a, 0x39, 0x0d, 0x1f, 0xfa, 0xda, 0x00, 0x38,
	0xbe, 0x91, 0xd0, 0xe5, 0x74, 0x06, 0x25, 0x6f, 0xb1, 0xda, 0x95, 0x53, 0xb4, 0x14, 0x94, 0x2b,
	0x31, 0x28, 0x4b, 0x68, 0x31, 0x06, 0x45, 0xff, 0x5d, 0x22, 0x20, 0xfc, 0x64, 0xc0, 0xb9, 0xa1,
	0xd1, 0x06, 0xa5, 0x15, 0x24, 0x7d, 0xc8, 0xab, 0xad, 0x4c, 0xa2, 0xaa, 0x10, 0xbd, 0x1f, 0x43,
	0xb4, 0x82, 0xea, 0x63, 0x92, 0x43, 0xd5, 0x09, 0x12, 0xe2, 0x37, 0x32, 0x4b, 0xea, 0xd6, 0x1c,
	0x95, 0xa5, 0xe4, 0x7d, 0x3c, 0x2a, 0x4b, 0x43, 0x57, 0x6f, 0xb2, 0x60, 0xe8, 0xb4, 0x82, 0xad,
	0xdf, 0x80, 0x79, 0x97, 0x74, 0x4f, 0x1e, 0xbd, 0x3e, 0xad, 0x82, 0x7d, 0x42, 0x09, 0x27, 0x4f,
	0x8c, 0x67, 0x99, 0xa3, 0xe6, 0x7e, 0x5e, 0xfc, 0x93, 0xf4, 0xce, 0x3f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x4a, 0x7a, 0x6c, 0x90, 0x62, 0x13, 0x00, 0x00,
}
