// Code generated by protoc-gen-grpc-js-client
// source: app.proto
// DO NOT EDIT!

/*
This is a RSVP based Ajax client for gRPC gateway JSON APIs.
*/

var xhr = require('grpc-xhr');

function appsHello(p, conf) {
    path = '/_appscode/api/seed/v1beta1/apps/hello'
    return xhr(path, 'GET', conf, p);
}

var services = {
    apps: {
        hello: appsHello
    }
};

module.exports = {appscode: {seed: {app: {v1beta1: services}}}};
